<?php $isTemplate = @$isTemplate == true; ?>

<tr data-divisionid="{$divisionId}">
    <td>
        <?php $elId = $fieldset->get('id'); ?>
        <?php echo $this->formHidden($elId); ?>

        <?php $elName = $fieldset->get('name'); ?>
        <?php if ($isTemplate): ?>
            <?php $elName->setAttribute('class', 'form-control input-sm'); ?>
            <?php echo $this->formElement($elName); ?>
        <?php else: ?>
            <?php echo $this->formHidden($elName); ?>
            <?php echo $this->escapeHtml($elName->getValue()); ?>
        <?php endif; ?>
    </td>
    <td class="col-sm-2" style="text-align:right; padding-right: 15px;"><a class="btn btn-xs btn-danger dropdivision" title="Remove Division"><i class="glyphicon glyphicon-trash"></i></a></td>
</tr>