<?php $isTemplate = @$isTemplate == true; ?>
<?php $elId = $fieldset->get('id'); ?>
<?php $elTeam = $fieldset->get('team'); ?>

<tr data-teamid="<?php echo $this->escapeHtmlAttr($elId->getValue()); ?>"<?php if (isset($index)): ?> data-teamindex="<?php echo $this->escapeHtmlAttr($index); ?>"<?php endif;?>>
    <td>
        <?php echo $this->formHidden($elId); ?>

        <?php if ($isTemplate || empty($elId->getValue())): ?>
            <?php $elId->setAttribute('class', 'form-control input-sm'); ?>
            <?php echo $this->formSelect($elTeam); ?>
        <?php else: ?>
            <?php echo $this->formHidden($elTeam); ?>
            <a href="<?php echo $this->url('zfcadmin/usarugbystats_teamadmin/edit',['id'=>$elTeam->getValue()]); ?>" target="_blank">
                <?php echo $this->escapeHtml($fieldset->getTeam()->getName()); ?>
            </a>
        <?php endif; ?>
        <?php echo $this->formElementErrors($elTeam); ?>
    </td>
    <td class="col-sm-2" style="text-align:right; padding-right: 15px;"><a class="btn btn-xs btn-danger dropteam" title="Remove Team"><i class="glyphicon glyphicon-trash"></i></a></td>
</tr>