<?php
$me = $this->zfcUserIdentity();
$role = $me->getRoleAssignment('team_admin');
?>

<div class="page-header">
  <div style="float:left; padding-right:12px;"><?=$this->gravatar($me->getEmail(), ['img_size' => '42']) ?></div>
  <h1><?= $this->escapeHtml($me->getDisplayName()); ?></h1>
</div>

<div class="row">
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">Upcoming Games</div>
      <?php if (count($upcomingMatches)): ?>
      <?php   echo $this->render('usa-rugby-stats/competition-frontend/partials/games-listing', ['matches' => $upcomingMatches, 'showScore' => false]); ?>
      <?php else: ?>
      <div class="panel-body">
        <div class="pull-center">Your teams are not participating in any upcoming matches.</div>
      </div>
      <?php endif; ?>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">Past Games</div>
      <?php if (count($pastMatches)): ?>
      <?php   echo $this->render('usa-rugby-stats/competition-frontend/partials/games-listing', ['matches' => $pastMatches, 'showScore' => true]); ?>
      <?php else: ?>
      <div class="panel-body">
        <div class="pull-center">Your teams have not participated in any past matches.</div>
      </div>
      <?php endif; ?>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">Your Teams</div>

      <ul class="list-group">
        <?php foreach ( $role->getManagedTeams() as $team ): ?>
        <li class="list-group-item"><?=$this->ursTeamLink($team); ?></li>
        <?php endforeach; ?>
      </ul>

    </div>
  </div>
</div>