<?php if ( ! $this->flags->{'match.signatures%visible'}->is_off() ): ?>
<?php $argv = $this->vars()->getArrayCopy(); ?>
<div class="panel panel-default">
    <div class="panel-heading">Match Signatures</div>

    <table class="table table-striped table-bordered competition-match-signatures">
        <thead<?php if (count($collection) == 0) echo ' style="display:none"'; ?>>
            <tr>
                <th>Type</th>
                <th>Signee</th>
                <?php if ( $this->flags->{'match.signatures'}->is_on() ): ?><th></th><?php endif; ?>
            </tr>
        </thead>
        <tbody>
            <?php foreach ( $collection as $idx => $fsSignature ): ?>
            <?php   echo $this->render('usa-rugby-stats/competition-admin/competition-admin/matches/signatures/signature', array_merge($argv, ['index' => $idx, 'fieldset' => $fsSignature])); ?>
            <?php endforeach; ?>
        </tbody>
        <?php if ( $this->flags->{'match.signatures'}->is_on() ): ?>
        <tfoot>
            <tr>
                <td colspan="3">
                    <a class="btn btn-sm btn-primary competition-match-signatures-addsignature" title="Add a Signature"><i class="glyphicon glyphicon-plus-sign"></i> Add a Signature</a>
                </td>
            </tr>
        </tfoot>
        <?php endif; ?>
    </table>

    <?php if ( $this->flags->{'match.signatures'}->is_on() ): ?>
    <script type="text/javascript">
        matchSignatureTemplate = '<?php echo $this->escapeJs($this->render('usa-rugby-stats/competition-admin/competition-admin/matches/signatures/signature', array_merge($argv, ['fieldset' => $collection->getTemplateElement(), 'isTemplate' => true]))); ?>';
        var matchSignatureIndex = <?php echo $this->escapeJs(count($collection)); ?>;

        $(document).on('click', '.competition-match-signatures .competition-match-signatures-addsignature', function() {
            $('.competition-match-signatures > thead').show();
            var html = matchSignatureTemplate.replace(/__sigindex__/g, matchSignatureIndex++);
            $('.competition-match-signatures > tbody').append(html);
        });
        $(document).on('click', '.competition-match-signatures .competition-match-signatures-removesignature', function() {
            if ( $(this).closest('tbody').find('tr').length < 2 ) {
                $('.competition-match-signatures > thead').hide();
            }
            $(this).closest('tr').remove();
        });
    </script>
    <?php endif; ?>

</div>
<?php endif; ?>