<div class="panel panel-default">
    <div class="panel-heading">Match Signatures</div>

    <table class="table table-striped table-bordered competition-match-signatures">
        <thead>
            <tr>
                <th>Type</th>
                <th>Signee</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php $elementCount = 0; ?>
            <?php foreach ( $collection as $fsSignature ): ?>
            <?php   if ( !empty($fsSignature->get('id')->getValue()) ): ?>
            <?php     echo $this->render('usa-rugby-stats/competition-admin/competition-admin/matches/signatures/signature', ['fieldset' => $fsSignature]); ?>
            <?php     $elementCount++; ?>
            <?php   endif; ?>
            <?php endforeach; ?>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="5">
                    <a class="btn btn-sm btn-primary competition-match-signatures-addsignature" title="Add a Signature"><i class="glyphicon glyphicon-plus-sign"></i> Add a Signature</a>
                </td>
            </tr>
        </tfoot>
    </table>

    <script type="text/javascript">
        matchSignatureTemplate = '<?php echo $this->escapeJs($this->render('usa-rugby-stats/competition-admin/competition-admin/matches/signatures/signature', ['fieldset' => $collection->getTemplateElement(), 'isTemplate' => true])); ?>';
        var matchSignatureIndex = <?php echo $this->escapeJs($elementCount); ?>;

        $(document).on('click', '.competition-match-signatures .competition-match-signatures-addsignature', function() {
            var html = matchSignatureTemplate.replace(/__sigindex__/g, matchSignatureIndex++);
            $('.competition-match-signatures > tbody').append(html);
        });
        $(document).on('click', '.competition-match-signatures .competition-match-signatures-removesignature', function() {
            $(this).closest('tr').remove();
        });
    </script>

</div>