<?php $canEdit = @$isTemplate || !$this->flags->{"match.signatures.$index"}->is_off(); ?>

<?php
$element = $fieldset->get('type');
$allTypes = $element->getValueOptions();

// Strip out any signature types the user is not allowed to add
if ( $this->flags->{'match.signatures.allowed_types'}->is_set() ) {
    $allowedTypes = [];
    foreach ( $allTypes as $atKey => $atLabel ) {
        if ( $this->flags->{'match.signatures.allowed_types'}->has($atKey) ) {
            $allowedTypes[$atKey] = $atLabel;
        }
    }
    $element->setValueOptions($allowedTypes);
}

?>

<tr>
    <td class="column column-type">
        <?php $element = $fieldset->get('type'); ?>
        <?php if ( $canEdit ): ?>
        <?php echo $this->formElement($element) ?>
        <?php else: ?>
        <?php   echo $this->escapeHtml(isset($allTypes[$element->getValue()]) ? $allTypes[$element->getValue()] : '???'); ?>
        <?php endif;?>
        <?php echo $this->formElementErrors($element); ?>
    </td>

    <td class="column signee">
        <?php $element = $fieldset->get('account'); ?>
        <?php if ( $canEdit ): ?>
        <?php echo $this->formElement($element) ?>
        <?php else: ?>
        <?php echo $this->ursPlayerLink($element->getValue()); ?>
        <?php endif;?>
        <?php echo $this->formElementErrors($element); ?>
    </td>

    <?php if ( $this->flags->{'match.signatures'}->is_on() ): ?>
    <td style="width:42px">
        <?php if ( $canEdit ) echo $this->formHidden($fieldset->get('id')); ?>
        <?php if ( @$isTemplate || $fieldset->get('type')->getValue() && $this->flags->{'match.signatures.allowed_types'}->has($fieldset->get('type')->getValue()) ): ?>
        <a class="btn btn-xs btn-danger competition-match-signatures-removesignature"><i class="glyphicon glyphicon-remove"></i></a>
        <?php endif; ?>
    </td>
    <?php endif; ?>
</tr>