<?php $canEdit = @$isTemplate || !$this->flags->{"match.signatures.$index"}->is_off(); ?>

<?php
// Strip out any signature types the user is not allowed to add
if ( $this->flags->{'match.signatures.allowed_types'}->is_set() ) {
    $element = $fieldset->get('type');
    $existingTypes = $element->getValueOptions();

    foreach ( $existingTypes as $atKey => $atLabel ) {
        if ( ! $this->flags->{'match.signatures.allowed_types'}->has($atKey) ) {
            unset($existingTypes[$atKey]);
        }
    }
    $element->setValueOptions($existingTypes);
}

?>

<tr>
    <td class="column column-type">
        <?php $element = $fieldset->get('type'); ?>
        <?php if ( $canEdit ): ?>
        <?php echo $this->formElement($element) ?>
        <?php else: ?>
        <?php echo $this->escapeHtml($element->getValue()); ?>
        <?php endif;?>
        <?php echo $this->formElementErrors($element); ?>
    </td>

    <td class="column signee">
        <?php $element = $fieldset->get('account'); ?>
        <?php if ( $canEdit ): ?>
        <?php echo $this->formElement($element) ?>
        <?php else: ?>
        <?php echo $this->escapeHtml($element->getValue()); ?>
        <?php endif;?>
        <?php echo $this->formElementErrors($element); ?>
    </td>

    <td style="width:42px">
        <?php if ( $canEdit ): ?>
        <?php echo $this->formHidden($fieldset->get('id')); ?>
        <a class="btn btn-xs btn-danger competition-match-signatures-removesignature"><i class="glyphicon glyphicon-remove"></i></a>
        <?php endif; ?>
    </td>
</tr>