<?php $form->setAttribute('class', 'form-horizontal'); ?>
<?php echo $this->form()->openTag($form) ?>

<?php $submitButton = $form->get('submit'); ?>
<?php $submitButton->setAttribute('class', 'btn btn-lg btn-success'); ?>

<?php if ( $form->has('userId') ) echo $this->formHidden($form->get('userId')); ?>

<div class="row">
    <div class="col-md-6">

        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Basic Account Details</h3>
          </div>
          <div class="panel-body">

            <div class="row form-group">
                <?php $element = $form->get('display_name'); ?>
                <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
                <?php $element->setAttribute('class', 'form-control'); ?>

                <?php echo $this->formLabel($element) ?>
                <div class="col-sm-8">
                    <?php echo $this->formElement($element) . $this->formElementErrors($element) ?>
                </div>
            </div>

            <div class="row form-group">
                <?php $element = $form->get('username'); ?>
                <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
                <?php $element->setAttribute('class', 'form-control'); ?>

                <?php echo $this->formLabel($element) ?>
                <div class="col-sm-8">
                    <?php echo $this->formElement($element) . $this->formElementErrors($element) ?>
                </div>
            </div>

            <div class="row form-group">
                <?php $element = $form->get('email'); ?>
                <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
                <?php $element->setAttribute('class', 'form-control'); ?>

                <?php echo $this->formLabel($element) ?>
                <div class="col-sm-8">
                    <?php echo $this->formElement($element) . $this->formElementErrors($element) ?>
                </div>
            </div>

          </div>
          <div class="panel-heading" style="border-top: 1px solid #ddd;">
            <h3 class="panel-title">Remote System Sync Settings</h3>
          </div>
          <div class="panel-body">

            <div class="row form-group">
                <?php $element = $form->get('remoteId'); ?>
                <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
                <?php $element->setAttribute('class', 'form-control'); ?>

                <?php echo $this->formLabel($element) ?>
                <div class="col-sm-8">
                    <?php echo $this->formElement($element); ?>
                    <p class="help-block">Used to associate this user with a record at the remote membership provider</p>
                    <?php echo $this->formElementErrors($element) ?>
                </div>
            </div>

          </div>
          <div class="panel-heading" style="border-top: 1px solid #ddd;">
            <h3 class="panel-title">Set Password</h3>
          </div>
          <div class="panel-body">

            <div class="row form-group">
                <?php $element = $form->get('password'); ?>
                <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
                <?php $element->setAttribute('class', 'form-control'); ?>

                <?php echo $this->formLabel($element) ?>
                <div class="col-sm-8">
                    <?php echo $this->formElement($element) . $this->formElementErrors($element) ?>
                </div>
            </div>

            <?php if ( $form->has('passwordVerify') ): ?>
            <div class="row form-group">
                <?php $element = $form->get('passwordVerify'); ?>
                <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
                <?php $element->setAttribute('class', 'form-control'); ?>

                <?php echo $this->formLabel($element) ?>
                <div class="col-sm-8">
                    <?php echo $this->formElement($element) . $this->formElementErrors($element) ?>
                    <?php if ( $form->has('reset_password') ): ?>
                    <span class="help-block">Leave both fields blank to keep current password.</span>
                    <?php endif; ?>
                </div>
            </div>
            <?php endif; ?>

            <?php if ( $form->has('reset_password') ): ?>
            <div class="row form-group">
                <?php $element = $form->get('reset_password'); ?>
                <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>

                <?php echo $this->formLabel($element) ?>
                <div class="col-sm-8">
                    <?php echo $this->formElement($element) . $this->formElementErrors($element) ?>
                </div>
            </div>
            <?php endif; ?>
          </div>
        </div>
    </div>

    <div class="col-md-6">
        <?php echo $this->render('usa-rugby-stats/account-admin/role-assignments', array('collection' => $form->get('roleAssignments')))?>
    </div>

</div>
<div class="clearfix"></div>
<div class="pull-left"><?php echo $this->formButton($submitButton); ?></div>

<?php if ($this->redirect): ?>
    <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>">
<?php endif ?>
<?php echo $this->form()->closeTag() ?>