<h1><?php echo $this->escapeHtml($entity->getName()); ?></h1>
<?php echo $this->render('usa-rugby-stats/competition-admin/competition-admin/navigation', ['page' => 'matches', 'entity' => $entity]); ?>

<?php
$form->prepare();
$form->setAttribute('action', $this->url('zfcadmin/usarugbystats_competitionadmin/edit/matches/create', ['id' => $entity->getId()]));
$form->setAttribute('method', 'post');
?>

<h2>Create New Match</h2>

<?php $form->setAttribute('class', 'form-horizontal'); ?>
<?php echo $this->form()->openTag($form) ?>

<?php $submitButton = $form->get('submit'); ?>
<?php $submitButton->setAttribute('class', 'btn btn-lg btn-success'); ?>

<div class="row">
    <div class="col-md-6">
        <?php echo $this->render('usa-rugby-stats/competition-admin/competition-admin/matches/form', $this->vars()); ?>
    </div>
    
    <div class="col-md-6">
   
    </div>
    
</div>

<div class="clearfix"></div>
<div class="pull-left"><?php echo $this->formButton($submitButton); ?></div>

<?php echo $this->form()->closeTag() ?>