<h1><?php echo $this->escapeHtml($competition->getName()); ?></h1>
<?php echo $this->render('usa-rugby-stats/competition-admin/competition-admin/navigation', ['page' => 'matches', 'entity' => $competition]); ?>

<?php
$form->prepare();
$form->setAttribute('action', $this->url('zfcadmin/usarugbystats_competitionadmin/edit/matches/create', ['id' => $competition->getId()]));
$form->setAttribute('method', 'post');
?>

<h2>Create New Match</h2>

<?php echo $this->render('usa-rugby-stats/competition-admin/competition-admin/matches/form', $this->vars()); ?>