<?php $fieldset = $form->get('match'); ?>

<?php echo $this->formHidden($fieldset->get('id')); ?>

<div class="panel panel-default">
    <div class="panel-heading">Match Details</div>
    <div class="panel-body">

        <?php if ( ! $this->flags->{'match.date_date%visible'}->is_off() ): ?>
        <div class="row form-group">
            <?php $element = $fieldset->get('date_date'); ?>
            <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
            <?php $element->setAttribute('class', 'form-control'); ?>

            <?php echo $this->formLabel($element) ?>
            <div class="col-sm-8">
                <?php if ( $this->flags->{'match.date_date'}->is_on() ): ?>
                <?php echo $this->formElement($element) ?>
                <script type="text/javascript">
                    $(function () {
                        $('input[name=match\\[date_date\\]]').datetimepicker({
                            pickTime: false,
                            format: 'YYYY-MM-DD'
                        });
                    });
                </script>
                <?php else: ?>
                <p class="form-control-static"><?php echo $this->escapeHtml($element->getValue()); ?></p>
                <?php endif;?>
                <?php echo $this->formElementErrors($element); ?>
            </div>
        </div>
        <?php endif; ?>
        <?php if ( ! $this->flags->{'match.date_time%visible'}->is_off() ): ?>
        <div class="row form-group">
            <?php $element = $fieldset->get('date_time'); ?>
            <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
            <?php $element->setAttribute('class', 'form-control'); ?>

            <?php echo $this->formLabel($element) ?>
            <div class="col-sm-3">
                <?php if ( $this->flags->{'match.date_time'}->is_on() ): ?>
                <?php echo $this->formElement($element) ?>
                <script type="text/javascript">
                    $(function () {
                        $('input[name=match\\[date_time\\]]').datetimepicker({
                            pickDate: false,
                            format: 'h:mm A'
                        });
                    });
                </script>
                <?php else: ?>
                <p class="form-control-static"><?php echo $this->escapeHtml($element->getValue()); ?></p>
                <?php endif;?>
                <?php echo $this->formElementErrors($element); ?>
            </div>
            <?php endif; ?>
            <?php if ( ! $this->flags->{'match.timezone%visible'}->is_off() ): ?>
            <div class="col-sm-5">
                <?php $element = $fieldset->get('timezone'); ?>
                <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
                <?php $element->setAttribute('class', 'form-control'); ?>

                <?php if ( $this->flags->{'match.timezone'}->is_on() ): ?>
                <?php   echo $this->formElement($element) ?>
                <?php else: ?>
                <p class="form-control-static"><?php echo $this->escapeHtml($element->getValueOptions()[$element->getValue()]); ?></p>
                <?php endif;?>
                <?php echo $this->formElementErrors($element); ?>
            </div>
        </div>
        <?php endif; ?>

        <?php if ( ! $this->flags->{'match.location%visible'}->is_off() ): ?>
        <div class="row form-group">
            <?php $element = $fieldset->get('location'); ?>
            <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
            <?php $element->setAttribute('class', 'form-control'); ?>

            <?php echo $this->formLabel($element) ?>
            <div class="col-sm-8">
                <?php if ( $this->flags->{'match.location'}->is_on() ): ?>
                <?php echo $this->formElement($element) ?>
                <?php else: ?>
                <p class="form-control-static"><?php echo $this->escapeHtml($element->getValue()); ?></p>
                <?php endif;?>
                <?php echo $this->formElementErrors($element); ?>
            </div>
        </div>
        <?php endif; ?>

        <?php if ( ! $this->flags->{'match.locationDetails%visible'}->is_off() ): ?>
        <div class="row form-group">
            <?php $element = $fieldset->get('locationDetails'); ?>
            <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
            <?php $element->setAttribute('class', 'form-control'); ?>
            <?php $element->setAttribute('rows', '3'); ?>

            <?php echo $this->formLabel($element) ?>
            <div class="col-sm-8">
                <?php if ( $this->flags->{'match.locationDetails'}->is_on() ): ?>
                <?php echo $this->formElement($element) ?>
                <?php else: ?>
                <p class="form-control-static"><?php echo $this->escapeHtml($element->getValue()); ?></p>
                <?php endif;?>
                <?php echo $this->formElementErrors($element); ?>
            </div>
        </div>
        <?php endif; ?>

        <?php if ( ! $this->flags->{'match.status%visible'}->is_off() ): ?>
        <div class="row form-group">
            <?php $element = $fieldset->get('status'); ?>
            <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
            <?php $element->setAttribute('class', 'form-control'); ?>
            <?php echo $this->formLabel($element) ?>
            <div class="col-sm-8">
                <?php if ( $this->flags->{'match.status'}->is_on() ): ?>
                <?php   echo $this->formElement($element) ?>
                <?php else: ?>
                <?php   $options = $element->getValueOptions(); ?>
                <p class="form-control-static"><?php echo $this->escapeHtml(isset($options[$element->getValue()]) ? $options[$element->getValue()] : '???'); ?></p>
                <?php endif;?>
            </div>
        </div>
        <?php endif; ?>

        <?php if ( ! $this->flags->{'match.isLocked%visible'}->is_off() ): ?>
        <div class="row form-group">
            <?php $element = $fieldset->get('isLocked'); ?>
            <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>

            <?php echo $this->formLabel($element) ?>
            <div class="col-sm-8">
                <?php if ( ! $this->flags->{'match.isLocked'}->is_off() ): ?>
                <?php echo $this->formElement($element) ?>
                <?php else: ?>
                <p class="form-control-static"><?php echo $this->escapeHtml($element->getValue() ? 'Yes' : 'No'); ?></p>
                <?php endif;?>
                <?php echo $this->formElementErrors($element); ?>
            </div>
        </div>
        <?php endif; ?>
    </div>
</div>