<h1><?php echo $this->escapeHtml($competition->getName()); ?></h1>
<?php echo $this->render('usa-rugby-stats/competition-admin/competition-admin/navigation', ['page' => 'matches', 'entity' => $competition]); ?>

<?php
$form->prepare();
$form->setAttribute('action', $this->url('zfcadmin/usarugbystats_competitionadmin/edit/matches/edit', ['id' => $competition->getId(), 'match' => $match->getId()]));
$form->setAttribute('method', 'post');
?>

<h2>Update Match <i><?php echo $this->escapeHtml($this->ursCompetitionMatchName($match)); ?></i></h2>

<?php $form->setAttribute('class', 'form-horizontal'); ?>
<?php echo $this->form()->openTag($form) ?>

<?php $submitButton = $form->get('submit'); ?>
<?php $submitButton->setAttribute('class', 'btn btn-lg btn-success'); ?>

<?php echo $this->render('usa-rugby-stats/competition-admin/competition-admin/matches/form', $this->vars()); ?>