<?php $argv = $this->vars()->getArrayCopy(); ?>

<?php $form->setAttribute('class', 'form-horizontal'); ?>
<?php echo $this->form()->openTag($form) ?>

<?php $submitButton = $form->get('submit'); ?>
<?php $submitButton->setAttribute('class', 'btn btn-lg btn-success'); ?>

<div class="row">
    <div class="col-md-6">
        <?php echo $this->render('usa-rugby-stats/competition-admin/competition-admin/matches/details', $argv); ?>
    </div>

    <div class="col-md-6">
        <?php echo $this->render('usa-rugby-stats/competition-admin/competition-admin/matches/signatures/collection', array_merge($argv, ['collection' => $form->get('match')->get('signatures')])); ?>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <?php echo $this->render('usa-rugby-stats/competition-admin/competition-admin/matches/team/form', array_merge($argv, ['fieldset' => $form->get('match')->get('teams')->get('H'), 'type' => 'H'])); ?>
    </div>

    <div class="col-md-6">
        <?php echo $this->render('usa-rugby-stats/competition-admin/competition-admin/matches/team/form', array_merge($argv, ['fieldset' => $form->get('match')->get('teams')->get('A'), 'type' => 'A'])); ?>
    </div>
</div>

<div class="clearfix"></div>
<div class="pull-left"><?php echo $this->formButton($submitButton); ?></div>

<?php echo $this->form()->closeTag() ?>