<?php $fieldset = $form->get('match'); ?>

<?php echo $this->formHidden($fieldset->get('id')); ?>

<div class="panel panel-default">
    <div class="panel-heading">Match Details</div>
    <div class="panel-body">

        <div class="row form-group">
            <?php $element = $fieldset->get('description'); ?>
            <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
            <?php $element->setAttribute('class', 'form-control'); ?>

            <?php echo $this->formLabel($element) ?>
            <div class="col-sm-8">
                <?php echo $this->formElement($element) . $this->formElementErrors($element) ?>
            </div>
        </div>

        <div class="row form-group">
            <?php $element = $fieldset->get('date'); ?>
            <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
            <?php $element->setAttribute('class', 'form-control'); ?>

            <?php echo $this->formLabel($element) ?>
            <div class="col-sm-8">
                <?php echo $this->formElement($element) . $this->formElementErrors($element) ?>
            </div>
        </div>

        <div class="row form-group">
            <?php $element = $fieldset->get('status'); ?>
            <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
            <?php $element->setAttribute('class', 'form-control'); ?>

            <?php echo $this->formLabel($element) ?>
            <div class="col-sm-8">
                <?php echo $this->formElement($element) . $this->formElementErrors($element) ?>
            </div>
        </div>

        <div class="row form-group">
            <?php $element = $fieldset->get('isLocked'); ?>
            <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>

            <?php echo $this->formLabel($element) ?>
            <div class="col-sm-8">
                <?php echo $this->formElement($element) . $this->formElementErrors($element) ?>
            </div>
        </div>
    </div>
</div>