<div class="panel panel-default">
    <div class="panel-heading">
        Role-based Access Control
        <div class="pull-right">
            <div class="btn-group">
                <a class="btn btn-primary btn-xs dropdown-toggle useraccount-rbacrole-add" data-toggle="dropdown">
                  <span class="glyphicon glyphicon-plus"></span> Add Role Assignment&nbsp;&nbsp;<span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu" id="AddRoleAssignmentButtonMenu">
<?php foreach ($collection->getTargetElement() as $item): ?>
                    <li><a href="javascript:;" data-key="<?php echo $this->escapeHtmlAttr($item->getName()); ?>"><?php echo $this->escapeHtml($item->getDisplayName()); ?></a></li>
<?php endforeach; ?>
                </ul>
            </div>
        </div>
     </div>
    <div class="panel-body">
        <div id="RoleAssignmentContainer">
            <?php
            $index = 0;
            foreach ( $collection as $item ) {
                if ( ! preg_match('{^UsaRugbyStats\\\\AccountAdmin\\\\Form\\\\Rbac\\\\RoleAssignment\\\\(.*)Fieldset$}is', get_class($item), $matches) ) {
                    continue;
                }

                echo $this->render('usa-rugby-stats/account-admin/role-assignments/' . $item->get('type')->getValue(), array(
                    'type' => $item->get('type')->getValue(),
                    'fieldset' => $item,
                    'index' => $index++,
                    'isTemplate' => false,
                ));
            }
            ?>
        </div>
    </div>
</div>

<script type="text/javascript">
    var roleAssignmentTemplate = {};
<?php foreach ( $collection->getTemplateElement() as $fsTmpl ): ?>
<?php   if ( preg_match('{^UsaRugbyStats\\\\AccountAdmin\\\\Form\\\\Rbac\\\\RoleAssignment\\\\(.*)Fieldset$}is', get_class($fsTmpl), $matches) ): ?>
<?php     $viewName = strtolower($fsTmpl->get('type')->getValue()); ?>
        roleAssignmentTemplate['<?=$viewName;?>'] = '<?php echo $this->escapeJs($this->render('usa-rugby-stats/account-admin/role-assignments/' . $viewName, ['fieldset' => $fsTmpl, 'isTemplate' => true, 'type' => $viewName, 'index' => '__index__'])); ?>';
<?php   endif; ?>
<?php endforeach; ?>
    var roleAssignmentIndex = <?php echo $this->escapeJs(count($collection)); // Not sure if this works ?>

    $(document).on('click', '#AddRoleAssignmentButtonMenu a[data-key]', function() {
        var html = roleAssignmentTemplate[$(this).attr('data-key')].replace(/__index__/g, roleAssignmentIndex++);
        $('#RoleAssignmentContainer').append(html);
    });
    $(document).on('click', '#RoleAssignmentContainer .rbac-assignment-delete', function() {
        $(this).closest('.rbac-assignment').remove();
    });
</script>
