<div class="nghide" style="display:none">

    <div id="game-header" class="row">

    	<div class="col-sm-6 home-team" ng-style="{backgroundImage: 'url(/assets/img/teamcoverimages/{{homeTeam.id}}.png) !important'}">
    		<div class="score">{{match.teams.H.score}}</div>
    		<h2><a ng-href="/team/{{homeTeam.id}}">{{homeTeam.name}}</a></h2>
    		<div class="team-logo"><img ng-src="/assets/img/teamlogos/{{homeTeam.id}}.png"></div>
    	</div>


    	<div class="col-sm-6 away-team" ng-style="{backgroundImage: 'url(/assets/img/teamcoverimages/{{awayTeam.id}}.png) !important'}">
    		<div class="score">{{match.teams.A.score}}</div>
    		<h2><a ng-href="/team/{{awayTeam.id}}">{{awayTeam.name}}</a></h2>
    		<div class="team-logo"><img ng-src="/assets/img/teamlogos/{{awayTeam.id}}.png"></div>
    	</div>

    </div>

    <div id="game-meta">
    	<ul>
    		<li>Date: {{match.date_date}}</li>
    		<li>Competition: <a ng-href="/competition/{{competition.id}}">{{competition.name}}</a></li>
    		<li>Kickoff: {{match.date_time}}</li>
    		<li>Location:
    		  <span ng-show="location.id">
                <a target="_blank" href="/location/{{location.id}}">{{location.name}}</a>
    		  </span>
    		  <span ng-hide="location.id">
    		    <a target="_blank" href="http://maps.google.com/maps/search/{{match.locationDetails|encodeUri}}">Map <i class="glyphicon glyphicon-map-marker"></i></a>
    		  </span>
    		</li>
    		<li ng-show="permissions['match'] && ( match.isLocked == '0' || permissions['match.isLocked'] )"><a ng-click="editDetails()"><span class="icon-compose"></span> Edit</a></li>
    	</ul>
    </div>

</div>