<h1><?php echo $this->escapeHtml($competition->getName()); ?></h1>
<?php echo $this->render('usa-rugby-stats/competition-frontend/competition/navigation', ['page' => 'matches', 'entity' => $competition]); ?>

<?php
$form->prepare();
$form->setAttribute('action', $this->url('usarugbystats_frontend_competition_match/create', array('cid' => $competition->getId())));
$form->setAttribute('method', 'post');
?>

<h2>Create New Match</h2>

<?php echo $this->render('usa-rugby-stats/competition-admin/competition-admin/matches/form', $this->vars()); ?>