
<h1 style="text-align:center">Are You Sure?</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
    
    <div class="alert alert-danger">Are you sure you want to remove this match?<br />All rosters, scores and game events relating to it will also be removed.</div>
    
        <div class="panel panel-default">
            <div class="panel-heading">Match Details</div>
            <div class="panel-body">
                <div class="row form-group">
                    <label class="col-sm-4 control-label">Home Team</label>
                    <div class="col-sm-8">
                        <?php if ( null !== $entity->getHomeTeam() ): ?>
                        <img height="23" src="<?php echo $this->escapeHtmlAttr($this->ursTeamLogoUrl($entity->getHomeTeam())); ?>"><?php echo $this->ursTeamLink($entity->getHomeTeam()); ?>
                        <?php else: ?>N/A<?php endif;?>
                    </div>
                </div>
                <div class="row form-group">
                    <label class="col-sm-4 control-label">Away Team</label>
                    <div class="col-sm-8">
                        <?php if ( null !== $entity->getAwayTeam() ): ?>
                        <img height="23" src="<?php echo $this->escapeHtmlAttr($this->ursTeamLogoUrl($entity->getAwayTeam())); ?>"><?php echo $this->ursTeamLink($entity->getAwayTeam()); ?>
                        <?php else: ?>N/A<?php endif;?>                    
                    </div>
                </div>
                <div class="row form-group">
                    <label class="col-sm-4 control-label">Date/Time</label>
                    <div class="col-sm-8">
                        <?=$this->escapeHtml($entity->getDate()->format('r')); ?>
                    </div>
                </div>
                <div class="row form-group">
                    <label class="col-sm-4 control-label">Location</label>
                    <div class="col-sm-8">
                        <?=$this->escapeHtml($this->ursCompetitionMatchLocationName($entity)); ?>
                    </div>
                </div>
                <div class="row form-group">
                    <label class="col-sm-4 control-label">Match Status</label>
                    <div class="col-sm-8">
                        <?=$this->escapeHtml($this->ursCompetitionMatchStatus($entity)); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div style="text-align:center">
<form action="<?php echo $this->url('usarugbystats_frontend_competition_match/delete', ['cid' => $competition->getId(), 'mid' => $entity->getId()]); ?>" method="POST">
  <input type="hidden" name="confirmed" value="Y" />
  <a class="btn btn-success" href="<?php echo $this->url('usarugbystats_frontend_competition', ['id' => $competition->getId()]); ?>">No, Abort! Abort!</a>
  <button type="submit" class="btn btn-danger">Yes, Remove It!</button>
</form>
</div>