<style>
.scoreboard .away-team h1, .scoreboard .home-team h1 {font-size: 28px; line-height: 58px; overflow: hidden; white-space: nowrap; text-transform: uppercase; }
.scoreboard .away-team h1 a, .scoreboard .home-team h1 a { color: #1D2C46;}
.scoreboard .away-team { float: left;}
.scoreboard .home-team { float: left;}
.scoreboard #score { display: inline-block; text-align: center; line-height: 74px; font-size: 48px; float: left; margin: 11px 20px 0 20px; color: #999; }
</style>

<div class="scoreboard">
  <div class="away-team">
    <h1 style="font-size: 200%;"><?=$this->ursTeamLink($match->getAwayTeam()); ?></h1>
  </div>
  <div id="score"><?=$this->escapeHtml($match->getAwayTeam()->getScore()); ?> -  <?=$this->escapeHtml($match->getHomeTeam()->getScore()); ?></div>
  <div class="home-team">
    <h1 style="font-size: 200%;"><?=$this->ursTeamLink($match->getHomeTeam()); ?></h1>
  </div>
</div>
<hr style="clear:both" />
<a href="<?=$this->url('usarugbystats_frontend_competition', ['id' => $match->getCompetition()->getId()]); ?>"><?=$this->escapeHtml($match->getCompetition()->getName()); ?></a>&nbsp;&mdash;&nbsp;
<?=$this->escapeHtml($match->getDate()->format('F j, Y')); ?>&nbsp;&mdash;&nbsp;
Kickoff @ <?=$this->escapeHtml($match->getDate()->format('H:i')); ?>&nbsp;&mdash;&nbsp;
Game iFrame
<hr style="clear:both" />



<div class="row">
  <?php foreach ( ['A', 'H'] as $teamkey ): ?>
  <?php   $teamMembership = $match->getTeam($teamkey); ?>
    <div class="col-sm-6">
    <div class="panel panel-default">
      <div class="panel-heading"><?=($teamkey == 'H' ? 'Home' : 'Opponent')?> Roster&nbsp;&mdash;&nbsp;<?=$this->escapeHtml($teamMembership->getTeam()->getName()); ?></div>

      <table class="table table-striped">
        <thead>
          <tr>
       	    <th>#</th>
       	    <th>Pos</th>
     	    <th>Player</th>
     	    <th>FR</th>
           </tr>
         </thead>
         <tbody>
           <?php foreach ( $teamMembership->getPlayers() as $player ): ?>
           <tr>
             <td><?=$this->escapeHtml($player->getNumber()); ?></td>
             <td><?=$this->escapeHtml($player->getPosition()); ?></td>
             <td><?=$this->ursPlayerLink($player->getPlayer()); ?></td>
             <td><?=$player->isFrontRow() ? '<i class="glyphicon glyphicon-ok"></i>' : ''; ?></td>
           </tr>
           <?php endforeach;?>
         </tbody>
      </table>

    </div>
  </div>
  <?php endforeach; ?>
</div>


<div class="panel panel-default">
  <div class="panel-heading">Game Summary</div>

  <table class="table table-striped">
    <thead>
      <tr>
   	    <th>Min</th>
   	    <th>Event</th>
 	    <th>Team</th>
 	    <th>Player</th>
       </tr>
     </thead>
     <tbody>
       <?php foreach ( $match->getEvents() as $event ): ?>
       <tr>
         <td><?=$this->escapeHtml($event->getMinute()); ?></td>
         <td><?=$this->escapeHtml($event->getType()); ?></td>
         <td><?=$this->ursTeamLink($event->getTeam()); ?></td>
         <?php if ( $event->getDiscriminator() == 'sub'): ?>
         <td>
           On&nbsp;&mdash;&nbsp;#<?=$this->escapeHtml($event->getPlayerOn()->getNumber()); ?> - <?=$this->ursPlayerLink($event->getPlayerOn()); ?><br />
           Off&nbsp;&mdash;&nbsp;#<?=$this->escapeHtml($event->getPlayerOff()->getNumber()); ?> - <?=$this->ursPlayerLink($event->getPlayerOff()); ?>
         </td>
         <?php else: ?>
         <td>#<?=$this->escapeHtml($event->getPlayer()->getNumber()); ?> -
            <?=$this->ursPlayerLink($event->getPlayer()); ?></td>
         <?php endif;?>
       </tr>
       <?php endforeach;?>
     </tbody>
  </table>

</div>

