<h1><?php echo $this->escapeHtml($entity->getName()); ?></h1>

<?php echo $this->render('usa-rugby-stats/competition-frontend/competition/navigation', ['page' => 'matches', 'entity' => $entity]); ?>


<div class="panel panel-default competition-divisions">
    <div class="panel-heading">
        Matches in this Competition
        <?php if ( $this->isGranted('competition.competition.match.create', $entity) ): ?>
        <div class="pull-right">
            <a class="btn btn-xs btn-success competition-divisions-add" title="Add Match" href="<?php echo $this->url('usarugbystats_frontend_competition_match/create', array('cid' => $entity->getId())); ?>">
                <i class="glyphicon glyphicon-plus-sign"></i>
            </a>
        </div>
        <?php endif; ?>
    </div>

<?php if ($this->paginator->count() > 0 ): ?>
<table class="table table-striped">
    <thead>
        <tr>
            <th style="with:25px"><?php echo $this->translate('ID') ?></th>
            <th><?php echo $this->translate('Details') ?></th>
            <th><?php echo $this->translate('Date/Time') ?></th>
            <th style="text-align:center"><?php echo $this->translate('Status') ?></th>
            <th style="text-align:center"><?php echo $this->translate('Score') ?></th>
            <th style="text-align:center"><?php echo $this->translate('Sigs') ?></th>
            <th style="text-align:center"><?php echo $this->translate('Locked') ?></th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($this->paginator as $match): ?>
        <tr>
            <td class="cell cell-id">
                <a href="<?php echo $this->url('usarugbystats_frontend_competition_match/view', array('cid' => $entity->getId(), 'mid' => $match->getId())); ?>">
                  <?php echo $this->escapeHtml($match->getId()); ?>
                </a>
            </td>
            <td class="cell cell-details">
                <?php echo $this->ursCompetitionMatchLink($match, 'linked-team-names'); ?><br />
                <i><?php echo $this->escapeHtml($match->getDescription() ?: ''); ?></i>
            </td>
            <td class="cell cell-date">
                <?php echo $this->escapeHtml($match->getDate()->format('Y-m-d @ H:i')); ?>
            </td>
            <td class="cell cell-status" style="text-align:center">
                <?php echo $this->escapeHtml($match->getStatus()); ?>
            </td>
            <td class="cell cell-score" style="text-align:center">
                <?php if ( in_array($match->getStatus(), ['F', 'HF', 'AF']) ): ?>
                <?php   echo $this->escapeHtml($match->getHomeTeam()->getScore()); ?> -
                <?php   echo $this->escapeHtml($match->getAwayTeam()->getScore()); ?>
                <?php endif; ?>
            </td>
            <td class="cell cell-signatures" style="text-align:center">
                <?php echo $this->escapeHtml($match->getSignatures()->count()); ?>
            </td>
            <td class="cell cell-signatures" style="text-align:center">
                <?php echo $this->escapeHtml($match->isLocked() ? 'Y' : 'N'); ?>
            </td>

            <td class="cell cell-ctrls">
                <a href="<?php echo $this->url('usarugbystats_frontend_competition_match/view', array('cid' => $entity->getId(), 'mid' => $match->getId())); ?>">
                    <?php echo $this->translate('View') ?>
                </a>
                <?php if ( $this->isGranted('competition.competition.match.update', $match) ): ?>
                 | <a href="<?php echo $this->url('usarugbystats_frontend_competition_match/update', array('cid' => $entity->getId(), 'mid' => $match->getId())); ?>">
                    <?php echo $this->translate('Edit') ?>
                </a>
                <?php endif; ?>
                <?php if ( $this->isGranted('competition.competition.match.delete', $match) ): ?>
                 | <a href="<?php echo $this->url('usarugbystats_frontend_competition_match/delete', array('cid' => $entity->getId(), 'mid' => $match->getId())); ?>">
                    <?php echo $this->translate('Delete') ?>
                </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="8">
                <?php echo $this->paginationControl($paginator, 'Sliding', 'usa-rugby-stats/competition-frontend/competition/match/list-pagination', ['entity' => $entity]); ?>
            </td>
        </tr>
    </tfoot>
</table>
<?php else: ?>
  <div class="panel-body">
    <div class="alert alert-warning" style="margin:0">There are no matches in this competition!</div>
  </div>
<?php endif; ?>

</div>