<?php
use UsaRugbyStats\Competition\Form\Fieldset\Competition\Match\MatchTeamPlayerFieldset;
$this->layout()->cover = 'usa-rugby-stats/competition-frontend/competition/match/cover';
$this->layout()->coverVars = $this->vars();
$this->layout()->mainClasses = array_merge((array)$this->layout()->mainClasses, ['game']);

$homeSide = $this->match->getTeam('H');
$homeTeam = $homeSide->getTeam();
$homeTeamRoster = $homeSide->getPlayers();
$awaySide = $this->match->getTeam('A');
$awayTeam = $awaySide->getTeam();
$awayTeamRoster = $awaySide->getPlayers();

//@TODO this should be encapsulated by the Competition object
$maxPlayers = empty($this->match->getCompetition()->getMaxPlayersOnRoster())
    ? ( $this->match->getCompetition()->getVariant() == '7s' ? '15' : '23' )
    : $this->match->getCompetition()->getMaxPlayersOnRoster();

// Get list of positions for this rugby variant
$positionKeys = json_encode(array_keys(MatchTeamPlayerFieldset::$positions[$this->match->getCompetition()->getVariant()]));
$positionNames = json_encode(array_values(MatchTeamPlayerFieldset::$positions[$this->match->getCompetition()->getVariant()]));

$isEditMode = $this->isGranted('competition.competition.update', $match) ? 'true' : 'false';

$this->inlineScript()->appendFile($this->basePath('/assets/js/vendor/angular.min.js'));
$this->inlineScript()->appendFile($this->basePath('/assets/js/vendor/angular-encode-uri.min.js'));
$this->inlineScript()->appendFile($this->basePath('/assets/js/vendor/ngRange.js'));
$this->inlineScript()->appendFile($this->basePath('/assets/js/app/competition.match.js'));

$this->inlineScript()->appendScript("
    angular.module('ursCompetitionMatch').run(function(\$rootScope) {
        \$rootScope.matchid = {$match->getId()};
        \$rootScope.compid = {$match->getCompetition()->getId()};
        \$rootScope.positionKeys = {$positionKeys};
        \$rootScope.positionNames = {$positionNames};
        \$rootScope.isEditMode = {$isEditMode};
    });
");

$this->layout()->containerAttributes = array_merge(
    (array)$this->layout()->containerAttributes,
    [
        'ng-app="ursCompetitionMatch"',
        'ng-controller="main"',
    ]
);

?>
<div class="nghide" style="display:none" ng-hide="loading">

    <div class="alert alert-success" ng-show="match.status == 'S' && permissions['match.status']">
        <span>This match is currently in progress.</span>
        <a class="btn btn-danger pull-right" style="margin-top: -7px" ng-click="resetMatchToNotStarted()">
            <span ng-hide="matchStatusIsChanging"><i class="glyphicon glyphicon-pause"></i> Revert to 'Not Started'</span>
            <span ng-show="matchStatusIsChanging"><i class="glyphicon glyphicon-refresh"></i> Updating...</span>
        </a>
    </div>

    <div id="content" class="col-sm-7">

        <div class="alert alert-info" ng-show="match.status == 'NS'">
            <span>This match has not yet started</span>
            <a ng-show="permissions['match.status']" class="btn btn-success pull-right" style="margin-top: -7px" ng-click="startMatch()">
                <span ng-hide="matchStatusIsChanging"><i class="glyphicon glyphicon-play"></i> Start it now</span>
                <span ng-show="matchStatusIsChanging"><i class="glyphicon glyphicon-refresh"></i> Updating...</span>
            </a>
        </div>

        <div class="panel" ng-hide="match.status == 'NS' || match.status == 'C'">
            <div class="title">
        		<h2><span class="icon-list"></span>Game Stream</h2>

        		<div class="pull-right" style="margin-right:12px; margin-top: -2px" ng-show="canAddEvents()">
        		  <a class="btn btn-xs btn-success" ng-click="addScore()"><i class="glyphicon glyphicon-plus"></i> Score</a>
        		  <a class="btn btn-xs btn-info" ng-click="addSub"><i class="glyphicon glyphicon-plus"></i> Sub</a>
        		  <a class="btn btn-xs btn-danger" ng-click="addCard()"><i class="glyphicon glyphicon-plus"></i> Card</a>
        		</div>

            </div>
            <table>
            	<thead>
            	   <tr>
            		 <th>MIN</th>
            		 <th>EVENT</th>
            		 <th>SIDE</th>
            		 <th>DETAILS</th>
            		 <th width="60" ng-show="canAddEvents()"></th>
            	   </tr>
            	</thead>
            	<tbody>
            	   <tr ng-repeat="(ekey,event) in matchEvents | orderBy:'minute'">
            		 <td ng-show="event.id > 0">{{event.minute}}'</td>
            		 <td ng-show="event.id > 0">
            		   {{formdata.event.types[event.event].name}} -
            		   {{formdata.event.types[event.event].optionLookup[event.type]}}
            		 </td>
            		 <td ng-show="event.id > 0 && event.side == 'H'">{{homeTeam.name}}</td>
            		 <td ng-show="event.id > 0 && event.side == 'A'">{{awayTeam.name}}</td>
            		 <td>
            		   <div ng-show="event.id > 0 && event.event != 'sub'">
            		      #{{extdata.teamPlayer[event.player].number}} -
            		      {{extdata.player[extdata.teamPlayer[event.player].acct].name}}
            		   </div>
            		   <div ng-show="event.id > 0 && event.event == 'sub'">
                		 Off: #{{extdata.teamPlayer[event.playerOff].number}} - {{extdata.player[extdata.teamPlayer[event.playerOff].acct].name}}<br />
                		 On: #{{extdata.teamPlayer[event.playerOn].number}} - {{extdata.player[extdata.teamPlayer[event.playerOn].acct].name}}
            		   </div>
            		 </td>
            		 <td ng-show="event.id > 0 && canAddEvents()" style="text-align:right; padding-right: 10px;">
            		   <a ng-click="trashEvent(event)" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-trash"></i></a>
            		 </td>
            	</tbody>
            </table>
        </div>
    </div>

    <aside class="col-sm-5" id="players">
        <div class="panel">
            <div class="title">
        		<h2><span class="icon-users"></span>Rosters</h2>
        		<div ng-show="permissions['match.teams.H.players'] || permissions['match.teams.A.players']">
        		    <a ng-hide="isEditingRoster" class="utility edit" ng-click="startEditingRoster()"><span class="icon-compose"></span>Edit Roster</a>
        		    <a ng-show="isEditingRoster" class="utility edit" ng-click="cancelEditingRoster()"><i class="glyphicon glyphicon-ban-circle"></i>&nbsp;&nbsp;Cancel</a>
        		    <a ng-show="isEditingRoster" class="utility edit" ng-click="saveChangesToRoster()">
                        <div ng-hide="matchRosterIsBeingSaved"><i class="glyphicon glyphicon-ok"></i>&nbsp;&nbsp;Save Changes</div>
                        <div ng-show="matchRosterIsBeingSaved"><i class="glyphicon glyphicon-refresh"></i>&nbsp;&nbsp; Saving...</div>
                    </a>
        		</div>
            </div>
            <table>
            	<thead>
                    <tr>
            	       <th class="home-player">{{homeTeam.name}}</th>
            		   <th></th>
            		   <th class="away-player">{{awayTeam.name}}</th>
            	   </tr>
            	</thead>
            	<tbody>
                	<tr ng-repeat="posKey in positionKeys">
                		<td class="home-player">
                		  <div ng-hide="isEditingRoster && permissions['match.teams.H.players']">
                		    <span ng-show="extdata.player[match.teams.H.players[posKey].player]">
                		      #{{match.teams.H.players[posKey].number}} -
                		      {{extdata.player[match.teams.H.players[posKey].player].name}}
                		    </span>
                		    <span ng-hide="extdata.player[match.teams.H.players[posKey].player]">&mdash;</span>
                		  </div>
                		  <div ng-show="isEditingRoster && permissions['match.teams.H.players']">
                		    <div class="row">
                		        <input type="hidden" ng-model="match.teams.H.players[posKey].id" name="match[teams][H][players][{{posKey}}][id]" />
                    		    <div class="col-xs-4">
                        		    <select ng-model="match.teams.H.players[posKey].number" class="form-control input-sm" name="match[teams][H][players][{{posKey}}][number]">
                        		        <option ng-repeat="n in [1,100] | range" ng-selected="match.teams.H.players[posKey].number == n || n == ($parent.$index+1)">{{n}}</option>
                        		    </select>
                                    <p ng-show="error.H[posKey].number" ng-repeat="(ek,em) in error.H[posKey].number" class="help-block">
                                        <i class="glyphicon glyphicon-exclamation-sign"></i> {{em}}
                                    </p>
                    		    </div>
                    		    <div class="col-xs-8">
                                    <select ng-model="match.teams.H.players[posKey].player" class="form-control input-sm" name="match[teams][H][players][{{posKey}}][player]">
                                        <option value="">Choose</option>
                                        <option
                                            ng-repeat="(key,player) in formdata.players.H"
                                            value="{{player.value}}"
                                            ng-selected="match.teams.H.players[posKey].player == player.value"
                                            ng-hide="player.value == ''"
                                        >
                                            {{player.label}}
                                        </option>
                                    </select>
                                    <p ng-show="error.H[posKey].player" ng-repeat="(ek,em) in error.H[posKey].player" class="help-block">
                                        <i class="glyphicon glyphicon-exclamation-sign"></i> {{em}}
                                    </p>
                                </div>
                            </div>
                		  </div>
                		</td>
                		<td ng-hide="isEditingRoster"><abbr title="{{positionNames[$index]}}">{{posKey}}</abbr></td>
                		<td ng-show="isEditingRoster">{{positionNames[$index]}}</td>
                		<td class="away-player">
                		  <div ng-hide="isEditingRoster && permissions['match.teams.A.players']">
                		    <span ng-show="extdata.player[match.teams.A.players[posKey].player]">
                		      #{{match.teams.A.players[posKey].number}} -
                		      {{extdata.player[match.teams.A.players[posKey].player].name}}
                		    </span>
                		    <span ng-hide="extdata.player[match.teams.A.players[posKey].player]">&mdash;</span>
                		  </div>
                		  <div ng-show="isEditingRoster && permissions['match.teams.A.players']">
                		    <input type="hidden" ng-model="match.teams.A.players[posKey].id" name="match[teams][A][players][{{posKey}}][id]" />
                		    <div class="row">
                    		    <div class="col-xs-4">
                        		    <select ng-model="match.teams.A.players[posKey].number" class="form-control input-sm"  name="match[teams][A][players][{{posKey}}][number]">
                        		        <option ng-repeat="n in [1,100] | range" ng-selected="match.teams.A.players[posKey].number == n || n == ($parent.$index+1)">{{n}}</option>
                        		    </select>
                                    <p ng-show="error.A[posKey].number" ng-repeat="(ek,em) in error.A[posKey].number" class="help-block">
                                        <i class="glyphicon glyphicon-exclamation-sign"></i> {{em}}
                                    </p>
                    		    </div>
                    		    <div class="col-xs-8">
                                    <select ng-model="match.teams.A.players[posKey].player" class="form-control input-sm"  name="match[teams][A][players][{{posKey}}][player]">
                                        <option value="">Choose</option>
                                        <option
                                            ng-repeat="(key,player) in formdata.players.A"
                                            value="{{player.value}}"
                                            ng-selected="match.teams.A.players[posKey].player == player.value"
                                            ng-hide="player.value == ''"
                                        >
                                            {{player.label}}
                                        </option>
                                    </select>
                                    <p ng-show="error.A[posKey].player" ng-repeat="(ek,em) in error.A[posKey].player" class="help-block">
                                        <i class="glyphicon glyphicon-exclamation-sign"></i> {{em}}
                                    </p>
                                </div>
                            </div>
                		  </div>
                		</td>
                	</tr>
            	</tbody>
            </table>
        </div>
    </aside>

    <div class="modal fade" id="MatchEventRemoveDialog" role="dialog" aria-labelledby="MatchEventRemoveDialogLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title" id="MatchEventRemoveDialogLabel">Are you sure?</h4>
          </div>
          <div class="modal-body">
            <p ng-hide="modalLoading">Are you sure you want to delete this game event?</p>
            <span ng-show="modalLoading" style="font-size: 2em;"><i class="glyphicon glyphicon-refresh"></i>&nbsp;&nbsp;Deleting...</span>
          </div>
          <div ng-hide="modalLoading" class="modal-footer" style="text-align:center">
            <button type="button" class="nobutton btn btn-success" data-dismiss="modal">No</button>
            <button type="button" class="yesbutton btn btn-danger">Yes</button>
          </div>
        </div>
      </div>
    </div>
    <?php $this->inlinescript()->appendScript("\$('MatchEventRemoveDialog').modal({show:false});"); ?>


    <div class="modal fade" id="MatchDetailsEditDialog" role="dialog" aria-labelledby="MatchDetailsEditDialogLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title" id="MatchDetailsEditDialogLabel">Update Match Details</h4>
          </div>
          <div class="modal-body">
            <span ng-show="modalLoading" style="font-size: 2em;"><i class="glyphicon glyphicon-refresh"></i>&nbsp;&nbsp;Loading...</span>
            <form ng-hide="modalLoading" class="form-horizontal" role="form">
              <div class="alert alert-success" ng-show="success">Match updated successfully!</div>
              <div class="alert alert-danger" ng-show="error">One or more errors occurred during save</div>
              <div class="form-group" ng-show="permissions['match.date']">
                <label for="match.date" class="col-sm-3 control-label">Date</label>
                <div class="col-sm-9">
                  <input ng-model="match.date" type="text" class="form-control" id="match.date" value="{{match.date}}">
                  <p ng-show="error['match.date']" ng-repeat="(ek,em) in error['match.date']" class="help-block">
                        <i class="glyphicon glyphicon-exclamation-sign"></i> {{em}}
                  </p>
                </div>
              </div>
              <div class="form-group" ng-show="permissions['match.location']">
                <label for="match.location" class="col-sm-3 control-label">Location</label>
                <div class="col-sm-9">
                    <select ng-model="match.location" class="form-control" id="match.location">
                        <option value="">No Location Specified</option>
                        <option
                            ng-repeat="(key,location) in formdata.locations"
                            value="{{location.value}}"
                            ng-selected="match.location == location.value"
                            ng-hide="location.value == ''"
                        >
                            {{location.label}}
                        </option>
                    </select>
                    <p ng-show="error['match.location']" ng-repeat="(ek,em) in error['match.location']" class="help-block">{{em}}</p>
                </div>
              </div>
              <div class="form-group" ng-show="permissions['match.locationDetails']">
                <label for="match.locationDetails" class="col-sm-3 control-label">Location Details</label>
                <div class="col-sm-9">
                  <textarea ng-model="match.locationDetails" class="form-control" id="match.locationDetails">{{match.locationDetails}}</textarea>
                  <p ng-show="error['match.locationDetails']" ng-repeat="(ek,em) in error['match.locationDetails']" class="help-block">
                        <i class="glyphicon glyphicon-exclamation-sign"></i> {{em}}
                  </p>
                </div>
              </div>
              <div class="form-group" ng-show="permissions['match.teams.H.team']">
                <label for="match.home" class="col-sm-3 control-label">Home Team</label>
                <div class="col-sm-9">
                    <select ng-model="match.teams.H.team" class="form-control" id="match.away">
                        <option
                            ng-repeat="(key,team) in formdata.teams"
                            value="{{team.value}}"
                            ng-selected="match.teams.H.team == team.value"
                            ng-hide="location.value == ''"
                        >
                            {{team.label}}
                        </option>
                    </select>
                    <p ng-show="error['match.teams.H.team']" ng-repeat="(ek,em) in error['match.teams.H.team']" class="help-block">
                        <i class="glyphicon glyphicon-exclamation-sign"></i> {{em}}
                    </p>
                </div>
              </div>
              <div class="form-group" ng-show="permissions['match.teams.A.team']">
                <label for="match.away" class="col-sm-3 control-label">Away Team</label>
                <div class="col-sm-9">
                    <select ng-model="match.teams.A.team" class="form-control" id="match.home">
                        <option
                            ng-repeat="(key,team) in formdata.teams"
                            value="{{team.value}}"
                            ng-selected="match.teams.A.team == team.value"
                            ng-hide="location.value == ''"
                        >
                            {{team.label}}
                        </option>
                    </select>
                    <p ng-show="error['match.teams.A.team']" ng-repeat="(ek,em) in error['match.teams.A.team']" class="help-block">
                        <i class="glyphicon glyphicon-exclamation-sign"></i> {{em}}
                    </p>
                </div>
              </div>
            </form>
          </div>
          <div ng-hide="modalLoading" class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary" ng-click="saveMatchDetails(match)">Save changes</button>
          </div>
        </div>
      </div>
    </div>
    <?php $this->inlinescript()->appendScript("\$('MatchDetailsEditDialog').modal({show:false});"); ?>
</div>
