language: php

php:
  - "5.5"
  - "5.4"

install:
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-php5 php5-curl php5-mysql php5-json
  - sudo a2enmod rewrite;
  - echo "$(cat .travisci/apache2.txt)" | sed -e "s,PATH,`pwd`/app,g" | sudo tee /etc/apache2/sites-available/default
  - sudo service apache2 restart
  - composer install --dev

before_script:
  - mysql -e 'create database usarugby'
  - mv behat.yml.dist behat.yml
  - echo "$(cat .travisci/config.php)" | sudo tee app/config.php
  - cp .travisci/doctrine.local.php.dist config/autoload/doctrine.local.php
  - cp .travisci/testing.local.php.dist config/autoload/testing.local.php

script:
  - for DIR in module config; do bin/php-cs-fixer fix -v --dry-run --fixers=-psr0,psr4 $DIR; done;
  - find module -type d -name "tests" | while read DIR; do ./bin/phpunit -c $DIR/phpunit.xml || exit 1; done;
  - #bin/behat --verbose
