language: php

php:
  - "5.4"
  - "5.5"
  - "5.6"
  - "hhvm"

install:
  - sudo apt-get update
  # install apache2 w/ FastCGI
  - bash .travisci/configure_apache2.sh
  # install application dependencies
  - composer install --dev

before_script:
  - mysql -e 'create database usarugby'
  - echo "$(cat .travisci/config.php)" | sudo tee app/config.php
  - cp .travisci/doctrine.local.php.dist config/autoload/doctrine.local.php
  - cp .travisci/testing.local.php.dist config/autoload/testing.local.php
  - ./bin/doctrine-module orm:schema-tool:create
  - ./bin/doctrine-module data-fixture:import 
  - sudo sh -e .travisci/start_selenium2.sh

script:
  - for DIR in module config; do bin/php-cs-fixer fix -v --dry-run --fixers=-psr0,psr4 $DIR; done;
  - find module -type f -name "phpunit.xml" | sort | while read FILE; do ./bin/phpunit -c $FILE || exit 1; done;
  # The version of Behat we use doesn't support PHP 5.6 (@see https://github.com/Behat/Behat/issues/525)
  - if [[ "$TRAVIS_PHP_VERSION" != "5.6" ]]; then find module -type f -name "behat.yml.dist" | sort | while read FILE; do REALFILE=${FILE/.dist/}; if [ ! -f "$REALFILE" ]; then cp "$FILE" "$REALFILE"; fi; ./bin/behat --config $REALFILE || exit 1; done; fi;

after_script:
  - curl -v http://localhost/account/login 
  - cat /tmp/apache2_default_access.log
  - cat /tmp/apache2_default_error.log
  - find /tmp -name "failure_*.html" | while read FILE; do echo $FILE; echo "======================" ; cat $FILE; echo -e "\n\n\n\n"; done;

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.6
    - php: hhvm

env:
  global:
    # IMGUR_CLIENT_ID
    secure: M2tUDMQkq4VlXKOCui3lypLEFth6a/RrXyt+gEdM8w2AyEggBUtTr5zr41xCEBVznovbQ8L1q+gvhxjLGo36Q6HqP1xsuNkd0+VgiqmfhUQ0m5NDilos7U9QVxHfqaEiPD3CvgOhB9f06kFm9oybKzXuduQB9t+PkuMUhoRw6HM=
