language: php

php:
  - "5.5"
  - "5.4"
  - "5.6"
  - "hhvm"

install:
  - sudo apt-get update
  # install apache2 w/ FastCGI
  - bash .travisci/configure_apache2.sh
  # install application dependencies
  - composer install --dev

before_script:
  - mysql -e 'create database usarugby'
  - echo "$(cat .travisci/config.php)" | sudo tee app/config.php
  - cp .travisci/doctrine.local.php.dist config/autoload/doctrine.local.php
  - cp .travisci/testing.local.php.dist config/autoload/testing.local.php
  - ./bin/doctrine-module orm:schema-tool:create
  - ./bin/doctrine-module data-fixture:import 
  - sh -e .travisci/start_selenium2.sh

script:
  - for DIR in module config; do bin/php-cs-fixer fix -v --dry-run --fixers=-psr0,psr4 $DIR; done;
  - find module -type d -name "phpunit.xml" | while read FILE; do ./bin/phpunit -c $FILE || exit 1; done;
  - find module -type f -name "behat.yml.dist" | while read FILE; do REALFILE=${FILE/.dist/}; if [ ! -f "$REALFILE" ]; then cp "$FILE" "$REALFILE"; fi; ./bin/behat --config $REALFILE || exit 1; done;

after_script:
  - curl -v http://localhost/account/login 
  - cat /tmp/apache2_default_access.log
  - cat /tmp/apache2_default_error.log

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.6
    - php: hhvm
