<?php
$validationGroup = $this->validationGroup ?: array();
$includeEverything = ( is_array($this->validationGroup) && empty($this->validationGroup) );
?>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Membership Details</h3>
  </div>
  <div class="panel-body">

    <div class="row form-group">
        <?php $element = $fieldset->get('firstName'); ?>
        <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
        <?php $element->setAttribute('class', 'form-control'); ?>

        <?php echo $this->formLabel($element) ?>
        <div class="col-sm-8">
            <?php if ( $includeEverything || in_array('firstName', $validationGroup, true) ): ?>
            <?php echo $this->formElement($element); ?>
            <?php else: ?>
            <p class="form-control-static"><?php echo $this->escapeHtml($element->getValue()); ?></p>
            <?php endif;?>
            <?php echo $this->formElementErrors($element) ?>
        </div>
    </div>

    <div class="row form-group">
        <?php $element = $fieldset->get('lastName'); ?>
        <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
        <?php $element->setAttribute('class', 'form-control'); ?>

        <?php echo $this->formLabel($element) ?>
        <div class="col-sm-8">
            <?php if ( $includeEverything || in_array('lastName', $validationGroup, true) ): ?>
            <?php echo $this->formElement($element); ?>
            <?php else: ?>
            <p class="form-control-static"><?php echo $this->escapeHtml($element->getValue()); ?></p>
            <?php endif;?>
            <?php echo $this->formElementErrors($element) ?>
        </div>
    </div>

    <div class="row form-group">
        <?php $element = $fieldset->get('telephoneNumber'); ?>
        <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
        <?php $element->setAttribute('class', 'form-control'); ?>

        <?php echo $this->formLabel($element) ?>
        <div class="col-sm-8">
            <?php if ( $includeEverything || in_array('telephoneNumber', $validationGroup, true) ): ?>
            <?php echo $this->formElement($element); ?>
            <?php else: ?>
            <p class="form-control-static"><?php echo $this->escapeHtml($element->getValue()); ?></p>
            <?php endif;?>
            <?php echo $this->formElementErrors($element) ?>
        </div>
    </div>

  </div>
</div>