<?php $loc = $match->getLocation(); ?>
<?php if ( $loc instanceof \UsaRugbyStats\Competition\Entity\Location ): ?>
<?php   echo $this->ursLocationLink($match->getLocation()); ?>
<?php elseif ( !empty($match->getLocationDetails()) ): ?>
<a href="https://www.google.com/maps/search/<?=$this->escapeHtmlAttr($this->escapeUrl($match->getLocationDetails())); ?>"<?php if(@$options['new_window']):?> target="_blank"<?php endif;?>>Map</a>
<?php else: ?>
N/A
<?php endif; ?>