<?php
use UsaRugbyStats\Competition\Entity\Competition\Match\MatchTeamPlayer;

$account = $this->player instanceof MatchTeamPlayer
    ? $this->player->getPlayer()
    : $this->player;
?>

<a href="<?=$this->url('usarugbystats_frontend_player', ['id' => $account->getId()]); ?>"<?php if(@$options['new_window']):?> target="_blank"<?php endif;?>>
  <?=$this->escapeHtml($this->ursPlayerName($this->player)); ?>
</a>