<?php
$form->prepare();
$form->setAttribute('action', $this->url('usarugbystats_frontend_union/update', ['id' => $entity->getId()]));
$form->setAttribute('method', 'post');
?>

<h1>Update Union</h1>

<?php $form->setAttribute('class', 'form-horizontal'); ?>
<?php echo $this->form()->openTag($form) ?>

<?php $submitButton = $form->get('submit'); ?>
<?php $submitButton->setAttribute('class', 'btn btn-lg btn-success'); ?>

<div class="row">
    <div class="col-md-6">

        <?php $fieldset = $form->get('union'); ?>

        <?php echo $this->formHidden($fieldset->get('id')); ?>

        <div class="panel panel-default">
            <div class="panel-heading">Union Details</div>
            <div class="panel-body">

                <div class="row form-group">
                    <?php $element = $fieldset->get('name'); ?>
                    <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
                    <?php $element->setAttribute('class', 'form-control'); ?>

                    <?php echo $this->formLabel($element) ?>
                    <div class="col-sm-8">
                        <?php echo $this->formElement($element) . $this->formElementErrors($element) ?>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="col-md-6">
        <?php echo $this->render('usa-rugby-stats/competition-admin/union-admin/form/teams', ['union' => @$this->entity, 'fieldset' => $fieldset]); ?>
    </div>
</div>
<div class="clearfix"></div>
<div class="pull-left"><?php echo $this->formButton($submitButton); ?></div>

<?php echo $this->form()->closeTag() ?>