<?php
$this->layout()->cover = 'usa-rugby-stats/competition-frontend/team/cover';
$this->layout()->coverVars = $this->vars();
?>

<div id="content" class="col-sm-8">

    <div class="panel">

    	<div id="team-view" class="title">
    		<ul class="tabs">
    			<li class="active"><h2><a href="#schedule" role="tab" data-toggle="tab"><span class="icon-calendar"></span>Schedule</a></h2></li>
    			<li><h2><a href="#players" role="tab" data-toggle="tab"><span class="icon-users"></span>Players</a></h2></li>
    		</ul>
    	</div>

         <div  class="tab-content">

         	<div class="tab-pane active" id="schedule">

                <?php if (count($this->matches) > 0): ?>
                <?php   echo $this->render('usa-rugby-stats/competition-frontend/partials/games-listing', ['matches' => $this->matches, 'relativeToTeam' => $team]); ?>
                <?php else: ?>
                <div class="schedule-is-empty">This team is not participating in any upcoming matches.</div>
                <?php endif; ?>
            </div>

            <div class="tab-pane" id="players">
                <?php if (count($this->players) > 0): ?>
            	<table class="panel">
            		<thead class="header">
            			<th>Players</th>
            			<th>POS</th>
            			<th>PTS</th>
            		</thead>
            		<tbody>
                		<?php foreach ( $this->players as $playerData ): ?>
                		<tr>
                			<td class="name">
                			    <?=$this->gravatar($playerData['player']->getEmail(), ['img_size' => 32])->setAttribs(['class' => 'media-image']); ?>
                			    <?=$this->ursPlayerLink($playerData['player']);?>
                			</td>
                			<td class="position"><?=$this->escapeHtml($playerData['position'] === false ? '--' : $playerData['position']);?></td>
                			<td class="points"><?=$this->escapeHtml(@$playerData['stats']['team'][$team->getId()]['career']['PTS'] ?: 0); ?></td>
                		</tr>
                        <?php endforeach;?>
                    </tbody>
                </table>
                <?php else: ?>
                <div class="team-has-no-players">This team does not have any active players.</div>
                <?php endif; ?>

        	</div>

        </div> <!-- end tab content  -->

    </div> <!-- end panel -->

</div>

<aside id="standings" class="col-sm-4">
    <div class="panel">
    	<div class="title">
    		<h2><span class="icon-list"></span>Standings</h2>
    		<a class="utility expand"><span class="icon-expand"></span>Full Standings</a>
    	</div>
    	<table>
    		<thead class="more">
    		  <tr>
    				<th class="team">Team</th>
    				<th class="more">GP</th>
    				<th class="record">R</th>
    				<th class="more">PF</th>
    				<th class="more">PA</th>
    				<th class="more">PD</th>
    				<th class="more">BT</th>
    				<th class="more">BL</th>
    				<th class="more">FF</th>
    				<th class="points">PTS</th>
    			</tr>
    		</thead>
    		<tbody>
    		    <?php foreach ( $this->leagueStandings['overall'] as $standingsRow): ?>
    		    <?php   $standingsRow instanceof TeamRecord; ?>
    		    <?php   $srTeam = $standingsRow->getTeam(); ?>
    			<tr<?php if ( $srTeam->getId() == $team->getId() ) echo ' class="active"';?>>
    				<td class="team"><a href="<?=$this->url('usarugbystats_frontend_team', ['id' => $srTeam->getId()]); ?>"><img src="<?=$this->escapeHtmlAttr($this->ursTeamLogoUrl($srTeam)); ?>"> <?=$this->escapeHtml($this->ursTeamName($srTeam)); ?></a></td>
    				<td class="more"><?=$this->escapeHtml($standingsRow->getTotalGames()); ?></td>
    				<td class="record"><?=$this->escapeHtml($standingsRow->getTotalWins()); ?>-<?=$this->escapeHtml($standingsRow->getTotalLosses()); ?></td>
    				<td class="more"><?=$this->escapeHtml($standingsRow->getScoreInFavor()); ?></td>
    				<td class="more"><?=$this->escapeHtml($standingsRow->getScoreAgainst()); ?></td>
    				<td class="more"><?=$this->escapeHtml($standingsRow->getScoreDifferential()); ?></td>
    				<td class="more"><?=$this->escapeHtml($standingsRow->getTryBonuses()); ?></td>
                    <td class="more"><?=$this->escapeHtml($standingsRow->getLossBonuses()); ?></td>
                    <td class="more"><?=$this->escapeHtml($standingsRow->getForfeits()); ?></td>
    				<td class="points"><?=$this->escapeHtml($standingsRow->getTotalPoints()); ?></td>
    			</tr>
    			<?php endforeach; ?>
            </tbody>
        </table>
    </div>
</aside>