<?php
use UsaRugbyStats\Competition\Entity\Competition;
$this->layout()->cover = 'usa-rugby-stats/competition-frontend/team/cover';
$this->layout()->coverVars = $this->vars();
?>

<div id="content" class="col-sm-8">

    <div class="panel">

    	<div id="team-view" class="title">
    		<ul class="tabs">
    			<li class="active"><h2><a href="#schedule" role="tab" data-toggle="tab"><span class="icon-calendar"></span>Schedule</a></h2></li>
    			<li><h2><a href="#players" role="tab" data-toggle="tab"><span class="icon-users"></span>Players</a></h2></li>
    		</ul>
    	</div>

         <div  class="tab-content">

         	<div class="tab-pane active" id="schedule">
                <?php if (count($this->matches) > 0): ?>
                <?php   echo $this->render('usa-rugby-stats/competition-frontend/partials/games-listing', ['matches' => $this->matches, 'relativeTo' => $team]); ?>
                <?php else: ?>
                <div class="schedule-is-empty">This team is not participating in any upcoming matches.</div>
                <?php endif; ?>
            </div>

            <div class="tab-pane" id="players">
                <?php if (count($this->players) > 0): ?>
            	<table class="panel">
            		<thead class="header">
            			<th>Players</th>
            			<th>POS</th>
            			<th>PTS</th>
            		</thead>
            		<tbody>
                		<?php foreach ( $this->players as $playerData ): ?>
                		<tr>
                			<td class="name">
                			    <?=$this->gravatar($playerData['player']->getEmail(), ['img_size' => 32])->setAttribs(['class' => 'media-image']); ?>
                			    <?=$this->ursPlayerLink($playerData['player']);?>
                			</td>
                			<td class="position"><?=$this->escapeHtml($playerData['position'] === false ? '--' : $playerData['position']);?></td>
                			<td class="points"><?=$this->escapeHtml(@$playerData['stats']['team'][$team->getId()]['career']['PTS'] ?: 0); ?></td>
                		</tr>
                        <?php endforeach;?>
                    </tbody>
                </table>
                <?php else: ?>
                <div class="team-has-no-players">This team does not have any active players.</div>
                <?php endif; ?>

        	</div>

        </div> <!-- end tab content  -->

    </div> <!-- end panel -->

</div>

<aside id="standings" class="col-sm-4">
    <div class="panel">
    	<div class="title">
    		<h2><span class="icon-list"></span>Standings</h2>
    		<a class="utility expand"><span class="icon-expand"></span>Full Standings</a>
    	</div>
    	<?php if ( $league instanceof Competition ): ?>
    	<div style="font-weight:bold; color: #223850;font-size: 13px;height: 35px;background: #eff0f3; padding: 8px 0 0 15px;overflow:hidden;text-overflow:ellipsis"><?php echo $this->ursCompetitionLink($league); ?></div>
    	<?php if ( isset($this->leagueStandings['by-division']) && !empty($this->leagueStandings['by-division']) ): ?>
        <?php   echo $this->render('usa-rugby-stats/competition-frontend/partials/standings-bydivision', ['standings' => $this->leagueStandings, 'isExpanded' => false] ); ?>
        <?php else: ?>
        <div class="team-has-no-league">This team does participate in a league.</div>
        <?php endif; ?>
        <?php else: ?>
        <div class="team-has-no-league">This team does participate in a league.</div>
        <?php endif; ?>
    </div>
</aside>