<?php
$form->prepare();
$form->setAttribute('action', $this->url('usarugbystats_frontend_team/update', ['id' => $entity->getId()]));
$form->setAttribute('method', 'post');
?>

<?php if ( $entity->getRemoteId() && $this->getHelperPluginManager()->has('ursRemoteDataSyncTriggerSyncTeam') ): ?>
<div class="pull-right">
    <a id="RosterSyncButton" class="btn btn-md btn-primary"><i class="glyphicon glyphicon-refresh"></i> Run Roster Sync</a>
    <?php echo $this->ursRemoteDataSyncTriggerSyncTeam($entity, 'TeamRosterSync', '#RosterSyncButton'); ?>
</div>
<?php endif; ?>

<h1 style="margin-top:0"><?=$this->ursTeamLink($entity);?> <i class="glyphicon glyphicon-chevron-right" style="font-size:0.75em"></i>&nbsp;&nbsp;Team Management</h1>

<?php $form->setAttribute('class', 'form-horizontal'); ?>
<?php echo $this->form()->openTag($form) ?>

<?php $submitButton = $form->get('submit'); ?>
<?php $submitButton->setAttribute('class', 'btn btn-lg btn-success'); ?>

<div class="row">
    <div class="col-md-6">

        <?php $fieldset = $form->get('team'); ?>

        <?php echo $this->formHidden($fieldset->get('id')); ?>

        <div class="panel panel-default">
            <div class="panel-heading">Team Details</div>
            <div class="panel-body">

                <?php if ( ! $this->flags->{'team.name%visible'}->is_off() ): ?>
                <div class="row form-group">
                    <?php $element = $fieldset->get('name'); ?>
                    <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
                    <?php $element->setAttribute('class', 'form-control'); ?>

                    <?php echo $this->formLabel($element) ?>
                    <div class="col-sm-8">
                        <?php if ( $this->flags->{'team.name'}->is_on() ): ?>
                        <?php echo $this->formElement($element) ?>
                        <?php else: ?>
                        <p class="form-control-static"><?php echo $this->escapeHtml($element->getValue()); ?></p>
                        <?php endif;?>
                        <?php echo $this->formElementErrors($element); ?>
                    </div>
                </div>
                <?php endif; ?>

                <?php if ( ! $this->flags->{'team.union%visible'}->is_off() ): ?>
                <div class="row form-group">
                    <?php $element = $fieldset->get('union'); ?>
                    <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
                    <?php $element->setAttribute('class', 'form-control'); ?>

                    <?php echo $this->formLabel($element) ?>
                    <div class="col-sm-8">
                        <?php if ( $this->flags->{'team.union'}->is_on() ): ?>
                        <?php echo $this->formElement($element) ?>
                        <?php else: ?>
                        <p class="form-control-static"><?php echo $this->ursUnionLink($element->getValue()); ?></p>
                        <?php endif;?>
                        <?php echo $this->formElementErrors($element); ?>
                    </div>
                </div>
                <?php endif; ?>

                <?php if ( ! $this->flags->{'team.city%visible'}->is_off() ): ?>
                <div class="row form-group">
                    <?php $element = $fieldset->get('city'); ?>
                    <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
                    <?php $element->setAttribute('class', 'form-control'); ?>

                    <?php echo $this->formLabel($element) ?>
                    <div class="col-sm-8">
                        <?php if ( $this->flags->{'team.city'}->is_on() ): ?>
                        <?php echo $this->formElement($element) ?>
                        <?php else: ?>
                        <p class="form-control-static"><?php echo $this->escapeHtml($element->getValue()); ?></p>
                        <?php endif;?>
                        <?php echo $this->formElementErrors($element); ?>
                    </div>
                </div>
                <?php endif; ?>

                <?php if ( ! $this->flags->{'team.state%visible'}->is_off() ): ?>
                <div class="row form-group">
                    <?php $element = $fieldset->get('state'); ?>
                    <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
                    <?php $element->setAttribute('class', 'form-control'); ?>

                    <?php echo $this->formLabel($element) ?>
                    <div class="col-sm-8">
                        <?php if ( $this->flags->{'team.state'}->is_on() ): ?>
                        <?php echo $this->formElement($element) ?>
                        <?php else: ?>
                        <p class="form-control-static"><?php echo $this->escapeHtml($element->getValue()); ?></p>
                        <?php endif;?>
                        <?php echo $this->formElementErrors($element); ?>
                    </div>
                </div>
                <?php endif; ?>
            </div>
            <div class="panel-heading" style="border-top: 1px solid #ddd;">Contact Information</div>
            <div class="panel-body">
                <?php if ( ! $this->flags->{'team.email%visible'}->is_off() ): ?>
                <div class="row form-group">
                    <?php $element = $fieldset->get('email'); ?>
                    <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
                    <?php $element->setAttribute('class', 'form-control'); ?>

                    <?php echo $this->formLabel($element) ?>
                    <div class="col-sm-8">
                        <?php if ( $this->flags->{'team.email'}->is_on() ): ?>
                        <?php echo $this->formElement($element) ?>
                        <?php else: ?>
                        <p class="form-control-static"><?php echo $this->escapeHtml($element->getValue()); ?></p>
                        <?php endif;?>
                        <?php echo $this->formElementErrors($element); ?>
                    </div>
                </div>
                <?php endif; ?>

                <?php if ( ! $this->flags->{'team.website%visible'}->is_off() ): ?>
                <div class="row form-group">
                    <?php $element = $fieldset->get('website'); ?>
                    <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
                    <?php $element->setAttribute('class', 'form-control'); ?>

                    <?php echo $this->formLabel($element) ?>
                    <div class="col-sm-8">
                        <?php if ( $this->flags->{'team.website'}->is_on() ): ?>
                        <?php echo $this->formElement($element) ?>
                        <?php else: ?>
                        <p class="form-control-static"><?php echo $this->escapeHtml($element->getValue()); ?></p>
                        <?php endif;?>
                        <?php echo $this->formElementErrors($element); ?>
                    </div>
                </div>
                <?php endif; ?>

                <?php if ( ! $this->flags->{'team.facebookHandle%visible'}->is_off() ): ?>
                <div class="row form-group">
                    <?php $element = $fieldset->get('facebookHandle'); ?>
                    <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
                    <?php $element->setAttribute('class', 'form-control'); ?>

                    <?php echo $this->formLabel($element) ?>
                    <div class="col-sm-8">
                        <?php if ( $this->flags->{'team.facebookHandle'}->is_on() ): ?>
                        <?php echo $this->formElement($element) ?>
                        <?php else: ?>
                        <p class="form-control-static"><?php echo $this->escapeHtml($element->getValue()); ?></p>
                        <?php endif;?>
                        <?php echo $this->formElementErrors($element); ?>
                    </div>
                </div>
                <?php endif; ?>

                <?php if ( ! $this->flags->{'team.twitterHandle%visible'}->is_off() ): ?>
                <div class="row form-group">
                    <?php $element = $fieldset->get('twitterHandle'); ?>
                    <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
                    <?php $element->setAttribute('class', 'form-control'); ?>

                    <?php echo $this->formLabel($element) ?>
                    <div class="col-sm-8">
                        <?php if ( $this->flags->{'team.twitterHandle'}->is_on() ): ?>
                        <?php echo $this->formElement($element) ?>
                        <?php else: ?>
                        <p class="form-control-static"><?php echo $this->escapeHtml($element->getValue()); ?></p>
                        <?php endif;?>
                        <?php echo $this->formElementErrors($element); ?>
                    </div>
                </div>
                <?php endif; ?>
            </div>
        </div>
    </div>

    <div class="col-sm-6">
        <div class="panel panel-default">
            <div class="panel-heading">Team Images</div>
            <div class="panel-body">
                <?php if ( ! $this->flags->{'team.new_logo%visible'}->is_off() ): ?>
                <div class="row form-group">
                    <?php $element = $fieldset->get('new_logo'); ?>
                    <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
                    <?php $element->setAttribute('class', 'form-control'); ?>

                    <?php echo $this->formLabel($element) ?>
                    <div class="col-sm-8">
                        <img src="<?php echo $this->ursTeamLogoUrl($entity); ?>" width="100" />
                        <?php if ( $this->flags->{'team.new_logo'}->is_on() ): ?>
                        <?php echo $this->formElement($element) ?>
                        <?php endif;?>
                        <?php echo $this->formElementErrors($element); ?>
                    </div>
                </div>
                <?php endif; ?>

                <?php if ( ! $this->flags->{'team.new_cover_image%visible'}->is_off() ): ?>
                <div class="row form-group">
                    <?php $element = $fieldset->get('new_cover_image'); ?>
                    <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
                    <?php $element->setAttribute('class', 'form-control'); ?>

                    <?php echo $this->formLabel($element) ?>
                    <div class="col-sm-8">
                        <img src="<?php echo $this->ursTeamCoverImageUrl($entity); ?>" width="100%" />
                        <?php if ( $this->flags->{'team.new_cover_image'}->is_on() ): ?>
                        <?php echo $this->formElement($element) ?>
                        <?php endif;?>
                        <?php echo $this->formElementErrors($element); ?>
                    </div>
                </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<div class="clearfix"></div>
<div class="pull-left"><?php echo $this->formButton($submitButton); ?></div>

