<div class="panel panel-default union-teams">
    <div class="panel-heading">
        Teams in this Union
        <div class="pull-right">
            <a class="btn btn-xs btn-success union-teams-add" title="Add Team"><i class="glyphicon glyphicon-plus-sign"></i></a>
        </div>
    </div>

    <?php $collAdmins = $fieldset->get('teams'); ?>

    <table class="table table-striped">
        <tbody style="border:0">

        <?php foreach ( $collAdmins->getFieldsets() as $fsTeam ): ?>
        <?php   echo $this->render('usa-rugby-stats/competition-admin/union-admin/form/teams/team', ['fieldset' => $fsTeam]); ?>
        <?php endforeach; ?>

        </tbody>
    </table>

    <script type="text/javascript">
        var managedTeamsSelectorTemplate = '<?php echo $this->escapeJs($this->render('usa-rugby-stats/competition-admin/union-admin/form/teams/team', ['fieldset' => $collAdmins->getTemplateElement(), 'isTemplate' => true])); ?>';
        var managedTeamIndex = <?php echo $this->escapeJs(count($collAdmins)); ?>;

        $(document).on('click', '.union-teams .union-teams-add', function() {
            var html = managedTeamsSelectorTemplate.replace(/__index__/g, managedTeamIndex++);
            $('.union-teams table tbody').append(html);
        });
        $(document).on('click', '.union-teams .dropteam', function() {
            $(this).closest('*[data-teamid]').remove();
        });
    </script>

</div>
