<?php
$this->headTitle($this->translate('Please sign in'));

$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
?>

<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4 col-lg-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Please sign in'); ?></h3>
            </div>
            <div class="panel-body">
                <?php echo $this->form()->openTag($form) ?>
                    <?php if ($this->redirect): ?>
                    <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
                    <?php endif ?>

                    <?php
                    $messages = $form->get('identity')->getMessages();
                    if ( count($messages) > 0  ) {
                        echo '<div class="alert alert-danger">The credentials you provided do not match any known account.  Please try again or contact support.</div>';
                    }
                    ?>

                    <fieldset>

                        <?php $element = $form->get('identity'); ?>
                        <?php $element->setAttributes(array('class' => 'form-control')); ?>
                        <div class="form-group">
                            <?php echo $this->formLabel($element) ?>
                            <?php echo $this->formInput($element); ?>
                        </div>

                        <?php $element = $form->get('credential'); ?>
                        <?php $element->setAttributes(array('class' => 'form-control')); ?>
                        <div class="form-group">
                            <?php echo $this->formLabel($element) ?>
                            <?php echo $this->formInput($element); ?>
                        </div>

                        <?php $element = $form->get('submit'); ?>
                        <?php $element->setAttributes(array('class' => 'btn btn-lg btn-primary btn-block', 'value' => 'Sign In')); ?>
                        <?php echo $this->formSubmit($element); ?>
                    </fieldset>
                <?php echo $this->form()->closeTag() ?>

                <?php if ($this->enableRegistration) : ?>
                <div style="margin-top: 15px; text-align: center">
                <?php echo $this->translate('Not registered?'); ?> <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>"><?php echo $this->translate('Sign up!'); ?></a>
                </div>
                <?php endif; ?>

            </div>
        </div>
    </div>

    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Sign In Assistance'); ?></h3>
            </div>
            <ul class="list-group">
              <a href="mailto:egeib@usarugby.org?subject=USARugbyStats.com Account Request"><li class="list-group-item"><strong>Don't have an account?</strong>  Click here.</li></a>
              <a href="mailto:egeib@usarugby.org?subject=USARugbyStats.com Password Reset"><li class="list-group-item"><strong>Can't remember your password?</strong>  Click here.</li></a>
            </ul>
        </div>
        
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('System Checkup'); ?></h3>
            </div>
            <div class="panel-body" style="padding: 8px" id="SystemCheckupPreamble">
                To use USA Rugby CMS your web browser must meet the following requirements:
            </div>
            <ul class="list-group" id="SystemCheckup">
              <li class="list-group-item list-group-item-danger" id="SystemCheckupNoJavascript">
                <div class="list-group-item-heading"><i class="glyphicon glyphicon-remove"></i>&nbsp;&nbsp;Javascript is not enabled</div>
                <p class="list-group-item-text"><a href="http://www.enable-javascript.com/" target="_blank">View instructions for enabling Javascript</a></p>
              </li>
              <li id="SystemCheckupJavascript" style="display:none" class="list-group-item list-group-item-success"><i class="glyphicon glyphicon-ok"></i>&nbsp;&nbsp;JavaScript enabled</li>
              <li id="SystemCheckupCookies" style="display:none" class="list-group-item">
                <span class="success"><i class="glyphicon"></i>&nbsp;&nbsp;Cookies enabled</span>
                <span class="failure">
                  <div class="list-group-item-heading"><i class="glyphicon"></i>&nbsp;&nbsp;Cookies are not enabled</div>
                  <p class="list-group-item-text"><a href="http://www.wikihow.com/Enable-Cookies-in-Your-Internet-Web-Browser" target="_blank">View instructions for enabling Cookies</a></p>
                </span>
              </li>
              <li id="SystemCheckupSession" style="display:none" class="list-group-item">
                <span class="success"><i class="glyphicon"></i>&nbsp;&nbsp;Session cookie</span>
                <span class="failure">
                  <div class="list-group-item-heading"><i class="glyphicon"></i>&nbsp;&nbsp;Session cookie is broken</div>
                  <p class="list-group-item-text">Please contact the Support Center for assistance</a></p>
                </span>
              </li>
            </ul>
        </div>
        <script type="text/javascript">

        $('#SystemCheckupNoJavascript').hide();
        $('#SystemCheckup span.success').hide();
        $('#SystemCheckup span.failure').hide();
        $('#SystemCheckupPreamble').hide();

        var SystemCheckup = {
            JavascriptCheckup: function() {
                return true;  // Duh
            },
            CookiesCheckup: function() {
                try {
                    document.cookie = 'cookietest=1';
                    var ret = document.cookie.indexOf('cookietest=') != -1;
                    document.cookie = 'cookietest=1; expires=Thu, 01-Jan-1970 00:00:01 GMT';
                    return ret;
                }
                catch (e) {
                  return false;
                }
            },
            SessionCheckup: function() {
                var ok = false;
                $.ajax({
                    url: '/api/session/sid',
                    async: false,
                    cache: false,
                    dataType: 'json',
                }).done(function(data) {
                    ok = ( typeof data.sid != undefined && data.sid == '<?=session_id()?>' );
                });
                return ok;
            },
            Execute: function() {
                var list = ['Javascript', 'Cookies', 'Session'];
                for ( var check in list ) {
                    var method = list[check] + 'Checkup';
                    var result = SystemCheckup[method]();

                    if ( result === false ) {
                        $('#SystemCheckupPreamble').show();
                    }

                    $('#SystemCheckup' + list[check] + ' i.glyphicon').addClass('glyphicon-' + (result === true ? 'ok' : 'remove'));
                    $('#SystemCheckup' + list[check]).addClass('list-group-item-' + (result === true ? 'success' : 'danger')).show();

                    $('#SystemCheckup' + list[check] + ' span.success').css('display', (result === true ? 'inline' : 'none'));
                    $('#SystemCheckup' + list[check] + ' span.failure').css('display', (result === false ? 'inline' : 'none'));
                }
            }
        }
        SystemCheckup.Execute();
        </script>
    </div>
    
</div>
