<div class="panel panel-default team-admins">
    <div class="panel-heading">
        Team Administrators
        <div class="pull-right">
            <a class="btn btn-xs btn-success team-admins-add" title="Add Administrator"><i class="glyphicon glyphicon-plus-sign"></i></a>
        </div>
    </div>

    <?php $collAdmins = $form->get('administrators'); ?>

    <table class="table table-striped">
        <tbody style="border:0">

        <?php foreach ( $collAdmins->getFieldsets() as $fsTeam ): ?>
        <?php   echo $this->render('usa-rugby-stats/competition-admin/team-admin/form/administrators/administrator', ['fieldset' => $fsTeam]); ?>
        <?php endforeach; ?>

        </tbody>
    </table>

    <script type="text/javascript">
        var administratorsSelectorTemplate = '<?php echo $this->escapeJs($this->render('usa-rugby-stats/competition-admin/team-admin/form/administrators/administrator', ['fieldset' => $collAdmins->getTemplateElement(), 'isTemplate' => true])); ?>';
        var administratorsIndex = <?php echo $this->escapeJs(count($collAdmins)); ?>;

        $(document).on('click', '.team-admins .team-admins-add', function() {
            var html = administratorsSelectorTemplate.replace(/__index__/g, administratorsIndex++);
            $('.team-admins table tbody').append(html);
        });
        $(document).on('click', '.team-admins .dropadmin', function() {
            $(this).closest('*[data-recordid]').remove();
        });
    </script>

</div>
