<?php
$form->prepare();
$form->setAttribute('action', $this->url('zfcadmin/usarugbystats_competitionadmin/edit/divisions', ['id' => $entity->getId()]));
$form->setAttribute('method', 'post');
?>

<h1><?php echo $this->escapeHtml($entity->getName()); ?></h1>

<?php echo $this->render('usa-rugby-stats/competition-admin/competition-admin/navigation', ['page' => 'divisions', 'entity' => $entity]); ?>

<?php
$form->setAttribute('class', 'form-horizontal');

echo $this->form()->openTag($form);

$submitButton = $form->get('submit');
$submitButton->setAttribute('class', 'btn btn-lg btn-success');

echo $this->render('usa-rugby-stats/competition-admin/competition-admin/form/divisions', ['competition' => $entity, 'fieldset' => $form->get('competition')]);
?>

<div class="clearfix"></div>
<div class="pull-left"><?php echo $this->formButton($submitButton); ?></div>

<?php echo $this->form()->closeTag() ?>