<h1><?php echo $this->escapeHtml($entity->getName()); ?></h1>

<?php echo $this->render('usa-rugby-stats/competition-admin/competition-admin/navigation', ['page' => 'details', 'entity' => $entity]); ?>

<?php 
$form->setAttribute('class', 'form-horizontal');

echo $this->form()->openTag($form);

$submitButton = $form->get('submit');
$submitButton->setAttribute('class', 'btn btn-lg btn-success');

?>

<div class="row">
    <div class="col-md-5">
        <?php echo $this->render('usa-rugby-stats/competition-admin/competition-admin/form', $this->vars()); ?>
    </div>
    
    <div class="col-md-7">
    </div>
    
</div>

<div class="clearfix"></div>
<div class="pull-left"><?php echo $this->formButton($submitButton); ?></div>

<?php echo $this->form()->closeTag() ?>