<?php $canEdit = $this->isGranted('competition.competition.update.details', $entity); ?>

<?php $fieldset = $form->get('competition'); ?>

<?php echo $this->formHidden($fieldset->get('id')); ?>

<div class="panel panel-default">
    <div class="panel-heading">Competition Details</div>
    <div class="panel-body">

        <div class="row form-group">
            <?php $element = $fieldset->get('name'); ?>
            <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
            <?php $element->setAttribute('class', 'form-control'); ?>

            <?php echo $this->formLabel($element) ?>
            <div class="col-sm-8">
                <?php if ( $canEdit ): ?>
                <?php echo $this->formElement($element) ?>
                <?php else: ?>
                <p class="form-control-static"><?php echo $this->escapeHtml($element->getValue()); ?></p>
                <?php endif;?>
                <?php echo $this->formElementErrors($element); ?>
            </div>
        </div>

        <div class="row form-group">
            <?php $element = $fieldset->get('variant'); ?>
            <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
            <?php $element->setAttribute('class', 'form-control'); ?>

            <?php echo $this->formLabel($element) ?>
            <div class="col-sm-8">
                <?php if ( $canEdit ): ?>
                <?php echo $this->formElement($element) ?>
                <?php else: ?>
                <p class="form-control-static"><?php echo $this->escapeHtml($element->getValue()); ?></p>
                <?php endif;?>
                <?php echo $this->formElementErrors($element); ?>
            </div>
        </div>

        <div class="row form-group">
            <?php $element = $fieldset->get('startDate'); ?>
            <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
            <?php $element->setAttribute('class', 'form-control'); ?>

            <?php echo $this->formLabel($element) ?>
            <div class="col-sm-8">
                <?php if ( $canEdit ): ?>
                <?php echo $this->formElement($element) ?>
                <?php else: ?>
                <p class="form-control-static"><?php echo $this->escapeHtml($element->getValue()); ?></p>
                <?php endif;?>
                <?php echo $this->formElementErrors($element); ?>
            </div>
        </div>

        <div class="row form-group">
            <?php $element = $fieldset->get('endDate'); ?>
            <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
            <?php $element->setAttribute('class', 'form-control'); ?>

            <?php echo $this->formLabel($element) ?>
            <div class="col-sm-8">
                <?php if ( $canEdit ): ?>
                <?php echo $this->formElement($element) ?>
                <?php else: ?>
                <p class="form-control-static"><?php echo $this->escapeHtml($element->getValue()); ?></p>
                <?php endif;?>
                <?php echo $this->formElementErrors($element); ?>
            </div>
        </div>
    </div>
</div>