<?php
$form = $this->profileForm;
$form->prepare();
$form->setAttribute('action', $this->url('ldc-user-profile'));
$form->setAttribute('method', 'post');

$count = count($form->getFieldsets());
$validationGroup = $form->getValidationGroup();
?>

<div class="page-header">
  <h1><?php echo $this->translate('Your USARugby Profile'); ?></h1>
</div>

<?php if ( ! $this->options->isEnabled() ): ?>
<div class="alert alert-info">The user profile functionality is currently disabled.</div>
<?php return; endif; ?>

<?php echo $this->form()->openTag($form) ?>

<div class="row">
  <?php foreach ( $form->getFieldsets() as $fieldset ): ?>
  <div class="col-md-<?=floor(12/$count);?>">
    <?php echo $this->render('ldc-user-profile/profile/extension/' . $fieldset->getName(), array('validationGroup' => @$validationGroup[$fieldset->getName()], 'fieldset' => $fieldset)); ?>
  </div>
  <?php endforeach;?>
</div>

<div class="text-center">
<?php echo $this->formButton($form->get('submit')->setAttributes(array('class' => 'btn btn-primary btn-lg'))); ?>
</div>

<?php echo $this->form()->closeTag() ?>