<?php
use UsaRugbyStats\Competition\Entity\Team;
use UsaRugbyStats\Competition\Entity\Competition;

$isRelativeToTeam = $this->relativeTo instanceof Team;
$isRelativeToCompetition = $this->relativeTo instanceof Competition;

$now = new DateTime();

$matchViewUrl = $this->url('usarugbystats_frontend_competition_match', ['cid' => $match->getCompetition()->getId(), 'mid' => $match->getId()]);
$compUrl  = $this->url('usarugbystats_frontend_competition', ['id' => $match->getCompetition()->getId()]);

?>
<tr data-matchdatetime="<?=$this->escapeHtmlAttr($match->getDate()->format('U')); ?>">
	<td class="date"><a href="<?=$this->escapeHtmlAttr($matchViewUrl); ?>"><?=$this->escapeHtml($match->getDate()->format('M jS')); ?></a></td>
	<td class="opponent">
	<?php if ( $isRelativeToTeam ): ?>
	<?php   $opponent = $match->getTeam('H')->getTeam()->getId() == $this->relativeTo->getId()
	                  ? $match->getTeam('A')
	                  : $match->getTeam('H');
	?>

	<?=($opponent->getType() == 'H' ? '@' : 'vs.'); ?> <img src="<?php echo $this->escapeHtmlAttr($this->ursTeamLogoUrl($opponent)); ?>"><?php echo $this->ursTeamLink($opponent); ?>
	<?php else: ?>
	<img src="<?php echo $this->escapeHtmlAttr($this->ursTeamLogoUrl($match->getTeam('A'))); ?>"><?php echo $this->ursTeamLink($match->getTeam('A')); ?>&nbsp;@
	<img src="<?php echo $this->escapeHtmlAttr($this->ursTeamLogoUrl($match->getTeam('H'))); ?>"><?php echo $this->ursTeamLink($match->getTeam('H')); ?>
	<?php endif;?>
	</td>
	<td class="result-time">
	<?php if ( $match->isCancelled() ): ?>
	   Cancelled
	<?php elseif ( $match->isNotStarted() || $now <= $match->getDate() ): ?>
	  <?=$this->escapeHtml($match->getDate()->format('H:i'));?>
	<?php elseif ( $isRelativeToTeam ): ?>
	<?php   $teamSide = $match->getTeam('H')->getTeam()->getId() == $this->relativeTo->getId() ? 'H' : 'A'; ?>
	<?php   $opponentSide = $teamSide == 'H' ? 'A' : 'H'; ?>
	<?php   $winningSide = $match->getWinningSide(); ?>
	<?php   if ( ! is_null($winningSide) ): ?>
	  <span><?=$this->escapeHtml($winningSide == 'D' ? 'D' : ( $winningSide == $teamSide ? 'W' : 'L')); ?></span>
	  <?=$this->escapeHtml($match->getTeam($teamSide)->getScore()); ?> -
	  <?=$this->escapeHtml($match->getTeam($opponentSide)->getScore()); ?>
	<?php   endif;?>
	<?php elseif ( $isRelativeToCompetition ): ?>
	  <?=$this->escapeHtml($match->getTeam('A')->getScore()); ?> -
	  <?=$this->escapeHtml($match->getTeam('H')->getScore()); ?>
	<?php endif; ?>
	</td>
	<td class="location">
    <?php if ( $match->getLocation() != null ): ?>
      <?php echo  $match->getLocation() ? $this->ursLocationLink($match->getLocation()) : ''; ?>
      <?php if ( $match->getLocation() && !empty($match->getLocationDetails()) ): ?>
        &nbsp;&dash;&nbsp;
      <?php endif; ?>
    <?php endif; ?>
    <?= $this->escapeHtml($match->getLocationDetails()); ?>
	</td>
	<?php if ( ! $isRelativeToCompetition ): ?>
	<td class="type"><?=$this->escapeHtml($match->getCompetition()->getTypeString());?></td>
	<?php endif; ?>
</tr>

