<?php
use UsaRugbyStats\Competition\Entity\Team;
use UsaRugbyStats\Competition\Entity\Competition;

$isRelativeToTeam = $this->relativeTo instanceof Team;
$isRelativeToCompetition = $this->relativeTo instanceof Competition;

$now = new DateTime();

$matchViewUrl = $this->url('usarugbystats_frontend_competition_match', ['cid' => $match->getCompetition()->getId(), 'mid' => $match->getId()]);
$compUrl  = $this->url('usarugbystats_frontend_competition', ['id' => $match->getCompetition()->getId()]);

if ( $isRelativeToTeam ): ?>

<tr data-matchdatetime="<?=$this->escapeHtmlAttr($match->getDate()->format('U')); ?>">
	<td class="date"><a href="<?=$this->escapeHtmlAttr($matchViewUrl); ?>"><?=$this->escapeHtml($match->getDate()->format('M jS')); ?></a></td>
	<td class="opponent">
	<?php   $opponent = $match->getTeam('H')->getTeam()->getId() == $this->relativeTo->getId()
	                  ? $match->getTeam('A')
	                  : $match->getTeam('H');
	?>

	<?=($opponent->getType() == 'H' ? '@' : 'vs.'); ?> <img src="<?php echo $this->escapeHtmlAttr($this->ursTeamLogoUrl($opponent)); ?>"><?php echo $this->ursTeamLink($opponent); ?>
	</td>
	<td class="result-time">
	<a href="<?=$this->escapeHtmlAttr($matchViewUrl); ?>">
	<?php if ( $match->isCancelled() ): ?>
	   Cancelled
	<?php elseif ( $match->isNotStarted() || $now <= $match->getDate() ): ?>
	  <?=$this->escapeHtml($match->getDate()->format('g:i a T'));?>
    <?php else: ?>
	<?php   $teamSide = $match->getTeam('H')->getTeam()->getId() == $this->relativeTo->getId() ? 'H' : 'A'; ?>
	<?php   $opponentSide = $teamSide == 'H' ? 'A' : 'H'; ?>
	<?php   $winningSide = $match->getWinningSide(); ?>
	<?php   if ( $match->isComplete() ): ?>
	  <span><?=$this->escapeHtml($winningSide == 'D' ? 'D' : ( $winningSide == $teamSide ? 'W' : 'L')); ?></span>
	<?php endif;?>
	  <?=$this->escapeHtml($match->getTeam($teamSide)->getScore()); ?> -
	  <?=$this->escapeHtml($match->getTeam($opponentSide)->getScore()); ?>
	<?php endif;?>
	</a>
	</td>

    <td class="type"><?=$this->escapeHtml($match->getCompetition()->getTypeString());?></td>

</tr>

<?php else: ?>

<tr data-matchdatetime="<?=$this->escapeHtmlAttr($match->getDate()->format('U')); ?>">

	<td class="date">
		<a href="<?=$this->escapeHtmlAttr($matchViewUrl); ?>"><?=$this->escapeHtml($match->getDate()->format('M jS')); ?></a>
	</td>

	<td class="away">
		<?php echo $this->ursTeamLink($match->getTeam('A')); ?><img src="<?php echo $this->escapeHtmlAttr($this->ursTeamLogoUrl($match->getTeam('A'))); ?>">
	</td>

	<td class="result-time">
	  <a href="<?=$this->escapeHtmlAttr($matchViewUrl); ?>">
		<?php if ( $match->isCancelled() ): ?>
		   Cancelled
		<?php elseif ( $match->isNotStarted() || $now <= $match->getDate() ): ?>
		  <?=$this->escapeHtml($match->getDate()->format('g:i a T'));?>
		<?php else: ?>
		  <?=$this->escapeHtml($match->getTeam('A')->getScore()); ?> -
		  <?=$this->escapeHtml($match->getTeam('H')->getScore()); ?>
		<?php endif; ?>
      </a>
	</td>

	<td class="home">
		<img src="<?php echo $this->escapeHtmlAttr($this->ursTeamLogoUrl($match->getTeam('H'))); ?>"><?php echo $this->ursTeamLink($match->getTeam('H')); ?>
	</td>

    <td class="type"><?=$this->escapeHtml($match->getCompetition()->getTypeString());?></td>
</tr>

<?php endif;?>

