<?php $now = new DateTime(); ?>

<table class="table table-striped" id="sort">
  <thead>
    <tr>
      <th width="100">Date</th>
      <th>Home</th>
      <?php if ( $showScore ): ?><th>Score</th><?php endif;?>
      <th>Opponent</th>
      <th>Location</th>
      <th>Status</th>
      <th width="40"></th>
     </tr>
   </thead>
   <tbody>
     <?php foreach ( $matches as $key => $match ): ?>
     <?php   $matchUrl = $this->url('usarugbystats_frontend_competition_match/view', ['cid' => $match->getCompetition()->getId(), 'mid' => $match->getId()]); ?>
     <?php   $matchEditUrl = $this->url('usarugbystats_frontend_competition_match/update', ['cid' => $match->getCompetition()->getId(), 'mid' => $match->getId()]); ?>
     <?php   $compUrl  = $this->url('usarugbystats_frontend_competition', ['id' => $match->getCompetition()->getId()]); ?>
     <tr>
       <td><?=$this->escapeHtml($match->getDate()->format('m/d/Y g:ia T')); ?></td>
       <td><?=$this->ursTeamLink($match->getHomeTeam()); ?></td>
       <?php if ( $showScore ): ?><td><?=$this->escapeHtml($match->hasTeam('H') ? $match->getHomeTeam()->getScore() : NULL); ?> - <?=$this->escapeHtml($match->hasTeam('A') ? $match->getAwayTeam()->getScore() : NULL); ?></td><?php endif;?>
       <td><?=$this->ursTeamLink($match->getAwayTeam()); ?></td>
       <td>
         <?php if ( $match->getLocation() != null ): ?>
           <?php echo  $match->getLocation() ? $this->ursLocationLink($match->getLocation()) : ''; ?>
           <?php if ( $match->getLocation() && !empty($match->getLocationDetails()) ): ?>
             &nbsp;&dash;&nbsp;
           <?php endif; ?>
         <?php endif; ?>
         <?= $this->escapeHtml($match->getLocationDetails()); ?>
       </td>
       <td style="text-align: center"><?=$match->getStatus(); ?></td>
       <td>
         <div class="btn-group pull-right">
           <a class="btn btn-info btn-sm dropdown-toggle" data-toggle="dropdown" href="#"><i class="glyphicon glyphglyphicon glyphicon-cog"></i>&nbsp;<span class="caret"></span>
           </a>
           <ul class="dropdown-menu">
             <li><a href="<?=$this->escapeHtmlAttr($matchUrl); ?>"><i class="glyphicon glyphicon-share"></i> Go to Game</a></li>
             <li><a href="<?=$this->escapeHtmlAttr($compUrl); ?>"><i class="glyphicon glyphicon-share"></i> Go to Competition</a></li>
             <?php if ( $this->isGranted('competition.competition.match.update', $match) ): ?>
             <li><a href="<?=$this->escapeHtmlAttr($matchEditUrl); ?>"><i class="glyphicon glyphicon-pencil"></i> Manage Game</a></li>
             <?php endif; ?>
           </ul>
        </div>
       </td>

    </tr>
    <?php endforeach; ?>
  </tbody>
</table>