<?php
use UsaRugbyStats\Competition\Entity\Team;
use UsaRugbyStats\Competition\Entity\Competition;

$isRelativeToTeam = $this->relativeTo instanceof Team;
$isRelativeToCompetition = $this->relativeTo instanceof Competition;

$now = new DateTime();
?>
<table class="responsive">
	<thead class="header">
		<th class="date">Date</th>
		<?php if ( $isRelativeToTeam ): ?>
		<th class="opponent">Opponent</th>
		<?php else: ?>
		<th class="opponent"></th>
		<?php endif;?>
		<th class="result-time">Result/Time</th>
		<?php if ( ! $isRelativeToCompetition ): ?>
		<th class="type">Type</th>
		<?php endif;?>
	</thead>
	<tbody>
	<?php $vars = $this->vars()->getArrayCopy(); ?>
	<?php foreach ( $this->matches as $match ): ?>
    <?php   echo $this->render('usa-rugby-stats/competition-frontend/partials/games-listing-row', $vars + ['match' => $match]); ?>
	<?php endforeach; ?>
	</tbody>
</table>

