<?php
use UsaRugbyStats\Competition\Entity\Team;
use UsaRugbyStats\Competition\Entity\Competition;

$isRelativeToTeam = $this->relativeTo instanceof Team;
$isRelativeToCompetition = $this->relativeTo instanceof Competition;

$now = new DateTime();
?>


	<?php if ( $isRelativeToTeam ): ?>

<table class="responsive">

	<thead class="header">
		<th class="date">Date</th>
		<th class="opponent">Opponent</th>
		<th class="result-time">Result/Time</th>
		<th class="type">Type</th>
		<th class="toolbox"></th>
	</thead>

	<?php else: ?>

<table class="competition responsive">

	<thead class="header">
		<th class="date">Date</th>
		<th class="opponent">Away</th>
		<th class="result-time">Result/Time</th>
		<th class="opponent">Home</th>
		<th class="type">Type</th>
		<th class="toolbox"></th>
	</thead>

	<?php endif;?>

	<tbody>
	<?php $vars = $this->vars()->getArrayCopy(); ?>
	<?php foreach ( $this->matches as $match ): ?>
    <?php   echo $this->render('usa-rugby-stats/competition-frontend/partials/games-listing-row', $vars + ['match' => $match, 'link_options' => @$link_options]); ?>
	<?php endforeach; ?>
	</tbody>
	
</table>

