<?php
use UsaRugbyStats\Competition\Entity\Team;

$isExpanded = @$this->isExpanded === true;
$relativeToTeam = $this->relativeTo instanceof Team;
$link_options = isset($link_options) ? (array)$link_options : array();

?>
<table>
	<thead>
	  <tr>
			<th class="team"><?=empty($this->divisionTitle) ? 'Team' : $this->escapeHtml($this->divisionTitle); ?></th>
			<th class="statcolumn<?=$isExpanded ? '' : ' more'; ?>">GP</th>
			<th class="statcolumn record">Record</th>
			<th class="statcolumn<?=$isExpanded ? '' : ' more'; ?>">W</th>
			<th class="statcolumn<?=$isExpanded ? '' : ' more'; ?>">L</th>
			<th class="statcolumn<?=$isExpanded ? '' : ' more'; ?>">T</th>
			<th class="statcolumn<?=$isExpanded ? '' : ' more'; ?>">PF</th>
			<th class="statcolumn<?=$isExpanded ? '' : ' more'; ?>">PA</th>
			<th class="statcolumn<?=$isExpanded ? '' : ' more'; ?>">PD</th>
			<th class="statcolumn<?=$isExpanded ? '' : ' more'; ?>">BT</th>
			<th class="statcolumn<?=$isExpanded ? '' : ' more'; ?>">BL</th>
			<th class="statcolumn<?=$isExpanded ? '' : ' more'; ?>">FF</th>
			<th class="statcolumn points">PTS</th>
		</tr>
	</thead>
	<tbody>
	    <?php foreach ( $this->standings as $standingsRow): ?>
	    <?php   $srTeam = $standingsRow->getTeam(); ?>
		<tr<?php if ( $relativeToTeam && $srTeam->getId() == $this->relativeTo->getId() ) echo ' class="active"';?>>
			<td class="team"><a href="<?=$this->url('usarugbystats_frontend_team', ['id' => $srTeam->getId()]); ?>"<?php if(@$link_options['new_window']) echo ' target="_blank"';?>><img src="<?=$this->escapeHtmlAttr($this->ursTeamLogoUrl($srTeam)); ?>"> <?=$this->escapeHtml($this->ursTeamName($srTeam)); ?></a></td>
			<td class="statcolumn<?=$isExpanded ? '' : ' more'; ?>"><?=$this->escapeHtml($standingsRow->getTotalGames()); ?></td>
			<td class="statcolumn record"><?=$this->escapeHtml($standingsRow->getTotalWins()); ?>-<?=$this->escapeHtml($standingsRow->getTotalLosses()); ?>-<?=$this->escapeHtml($standingsRow->getTotalTies()); ?></td>
			<td class="statcolumn<?=$isExpanded ? '' : ' more'; ?>"><?=$this->escapeHtml($standingsRow->getTotalWins()); ?></td>
			<td class="statcolumn<?=$isExpanded ? '' : ' more'; ?>"><?=$this->escapeHtml($standingsRow->getTotalLosses()); ?></td>
			<td class="statcolumn<?=$isExpanded ? '' : ' more'; ?>"><?=$this->escapeHtml($standingsRow->getTotalTies()); ?></td>

			<td class="statcolumn<?=$isExpanded ? '' : ' more'; ?>"><?=$this->escapeHtml($standingsRow->getScoreInFavor()); ?></td>
			<td class="statcolumn<?=$isExpanded ? '' : ' more'; ?>"><?=$this->escapeHtml($standingsRow->getScoreAgainst()); ?></td>
			<td class="statcolumn<?=$isExpanded ? '' : ' more'; ?>"><?=$this->escapeHtml($standingsRow->getScoreDifferential()); ?></td>
			<td class="statcolumn<?=$isExpanded ? '' : ' more'; ?>"><?=$this->escapeHtml($standingsRow->getTryBonuses()); ?></td>
            <td class="statcolumn<?=$isExpanded ? '' : ' more'; ?>"><?=$this->escapeHtml($standingsRow->getLossBonuses()); ?></td>
            <td class="statcolumn<?=$isExpanded ? '' : ' more'; ?>"><?=$this->escapeHtml($standingsRow->getForfeits()); ?></td>
			<td class="statcolumn points"><?=$this->escapeHtml($standingsRow->getTotalPoints()); ?></td>
		</tr>
		<?php endforeach; ?>
    </tbody>
</table>