<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Account Details</h3>
  </div>
  <div class="panel-body">
    <div class="row form-group">
        <?php $element = $fieldset->get('id'); ?>
        <?php $element->setLabel('Account ID'); ?>
        <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
        <?php $element->setAttribute('class', 'form-control'); ?>

        <?php echo $this->formLabel($element) ?>
        <div class="col-sm-8">
            <p class="form-control-static"><?php echo $this->escapeHtml($element->getValue()); ?></p>
            <?php echo $this->formElementErrors($element) ?>
        </div>
    </div>

    <div class="row form-group">
        <?php $element = $fieldset->get('display_name'); ?>
        <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
        <?php $element->setAttribute('class', 'form-control'); ?>

        <?php echo $this->formLabel($element) ?>
        <div class="col-sm-8">
            <p class="form-control-static"><?php echo $this->escapeHtml($element->getValue()); ?></p>
            <?php echo $this->formElementErrors($element) ?>
        </div>
    </div>

    <div class="row form-group">
        <?php $element = $fieldset->get('username'); ?>
        <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
        <?php $element->setAttribute('class', 'form-control'); ?>

        <?php echo $this->formLabel($element) ?>
        <div class="col-sm-8">
            <p class="form-control-static"><?php echo $this->escapeHtml($element->getValue()); ?></p>
            <?php echo $this->formElementErrors($element) ?>
        </div>
    </div>

    <div class="row form-group">
        <?php $element = $fieldset->get('email'); ?>
        <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
        <?php $element->setAttribute('class', 'form-control'); ?>

        <?php echo $this->formLabel($element) ?>
        <div class="col-sm-8">
            <p class="form-control-static"><?php echo $this->escapeHtml($element->getValue()); ?></p>
            <?php echo $this->formElementErrors($element) ?>
        </div>
    </div>

  </div>
  <div class="panel-heading" style="border-top: 1px solid #ddd;">
    <h3 class="panel-title">Change your Password</h3>
  </div>
  <div class="panel-body">

    <div class="row form-group">
        <?php $element = $fieldset->get('password'); ?>
        <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
        <?php $element->setAttribute('class', 'form-control'); ?>

        <?php echo $this->formLabel($element) ?>
        <div class="col-sm-8">
            <?php echo $this->formElement($element) . $this->formElementErrors($element) ?>
        </div>
    </div>

    <div class="row form-group">
        <?php $element = $fieldset->get('passwordVerify'); ?>
        <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
        <?php $element->setAttribute('class', 'form-control'); ?>

        <?php echo $this->formLabel($element) ?>
        <div class="col-sm-8">
            <?php echo $this->formElement($element) . $this->formElementErrors($element) ?>
            <span class="help-block">Leave fields blank to keep current password.</span>
        </div>
    </div>
  </div>
</div>