<h1>Locations</h1>

<div class="filter-bar" style="margin-bottom: 25px">
    <div class="row">
        <div class="col-sm-6">
            <div class="row">
                <form role="form" method="GET" action="<?php echo $this->url('zfcadmin/usarugbystats_locationadmin/search') ?>">
                  <div class="col-xs-10">
                    <input name="q" type="search" class="form-control" id="userSearch" placeholder="Enter fragment of location name, address, or coordinates...">
                  </div>
                  <div class="col-xs-2" style="padding-left:0"><button type="submit" class="btn btn-default">Search</button></div>
                </form>
            </div>
        </div>
        <div class="col-sm-4"></div>
        <div class="col-xs-2">
            <?php if ( $this->isGranted('competition.location.create') ): ?>
            <a class="btn btn-large btn-primary" href="<?php echo $this->url('zfcadmin/usarugbystats_locationadmin/create'); ?>">Add New Location</a>
            <?php endif; ?>
        </div>
    </div>
</div>

<?php if ($this->paginator->count() == 0 ): ?>
<div class="alert alert-warning">There are no locations!</div>
<?php endif; ?>

<?php if ($this->paginator->count() > 0 ): ?>
<table class="table table-striped">
    <thead>
        <tr>
            <th><?php echo $this->translate('ID') ?></th>
            <th><?php echo $this->translate('Name') ?></th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($this->paginator as $entity): ?>
        <tr>
            <td class="cell cell-id" style="width:50px">
                <?php echo $this->escapeHtml($entity->getId()); ?>
            </td>
            <td class="cell cell-name">
                <?php echo $this->escapeHtml($entity->getName()); ?>
            </td>
            <td class="col-sm-1 cell cell-ctrls">
                <a href="<?php echo $this->url('zfcadmin/usarugbystats_locationadmin/edit', array('id' => $entity->getId())); ?>">
                    <?php echo $this->translate('Edit') ?>
                </a>
                |
                <a href="<?php echo $this->url('zfcadmin/usarugbystats_locationadmin/remove', array('id' => $entity->getId())); ?>">
                    <?php echo $this->translate('Delete') ?>
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">
                <?php echo $this->paginationControl($this->users, 'Sliding', 'usa-rugby-stats/competition-admin/location-admin/search/pagination', ['q' => $q]); ?>
            </td>
        </tr>
    </tfoot>
</table>
<?php endif; ?>