<?php $canEdit = $this->flags->{"match.teams.$matchSideKey.events"}->is_on(); ?>

<table class="table" style="margin-bottom: 0;">
    <tbody style="border: 0;">
        <tr>
            <td>Type:</td>
            <td>
                <?php $element = $fieldset->get('type'); ?>
                <?php $element->setAttributes(['class' => 'input-sm']); ?>
                <?php if ( $canEdit ): ?>
                <?php   echo $this->formElement($element) ?>
                <?php else: ?>
                <?php echo $this->escapeHtml($element->getValue()); ?>
                <?php endif;?>
                <?php echo $this->formElementErrors($element); ?>
            </td>
        </tr>
        <tr>
            <td>On:</td>
            <td>
                <?php $element = $fieldset->get('playerOn'); ?>
                <?php $element->setAttributes(['class' => 'input-sm']); ?>
                <?php if ( $canEdit ): ?>
                <?php   echo $this->formElement($element) ?>
                <?php else: ?>
                <?php echo $this->escapeHtml($element->getValue()); ?>
                <?php endif;?>
                <?php echo $this->formElementErrors($element); ?>
            </td>
        </tr>
        <tr>
            <td>Off:</td>
            <td>
                <?php $element = $fieldset->get('playerOff'); ?>
                <?php $element->setAttributes(['class' => 'input-sm']); ?>
                <?php if ( $canEdit ): ?>
                <?php   echo $this->formElement($element) ?>
                <?php else: ?>
                <?php echo $this->escapeHtml($element->getValue()); ?>
                <?php endif;?>
                <?php echo $this->formElementErrors($element); ?>
            </td>
        </tr>
    </tbody>
</table>