<div class="page-header">
  <?php if ( $this->isGranted('competition.location.update', $location) ):?>
  <div class="pull-right" style="margin-top:5px">
    <a class="btn btn-primary" href="<?=$this->url('usarugbystats_frontend_location/update', ['id' => $location->getId()]); ?>"><i class="glyphicon glyphglyphicon glyphicon-cog"></i> Edit Location</a>
  </div>
  <?php endif; ?>
  <h1><?= $this->escapeHtml($location->getName()); ?></h1>
</div>

<div class="row">
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">Upcoming Matches at this Location</div>
      <?php if (count($upcomingMatches)): ?>
      <?php   echo $this->render('usa-rugby-stats/competition-frontend/partials/games-listing', ['matches' => $upcomingMatches, 'showScore' => false]); ?>
      <?php else: ?>
      <div class="panel-body">
        <div class="pull-center">This location does not have upcoming matches.</div>
      </div>
      <?php endif; ?>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">Past Matches at this Location</div>
      <?php if (count($pastMatches)): ?>
      <?php   echo $this->render('usa-rugby-stats/competition-frontend/partials/games-listing', ['matches' => $pastMatches, 'showScore' => false]); ?>
      <?php else: ?>
      <div class="panel-body">
        <div class="pull-center">This location does not have past matches.</div>
      </div>
      <?php endif; ?>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">Location Details</div>
      <div class="panel-body">
        <?php if ( $location->getAddress() ): ?>
        <?php echo $this->escapeHtml($location->getAddress()); ?><br /></li>
        <?php endif; ?>
        <?php if ( $location->getCoordinates() ): ?>
        <a href="https://www.google.com/maps/@<?php echo $this->escapeUrl(preg_replace('/\s/', '', $location->getCoordinates())); ?>,16z" target="_blank">@ <?=$this->escapeHtml($location->getCoordinates()) ?></a>
        <?php endif; ?>
      </div>

        <?php if ( $location->getAddress() || $location->getCoordinates() ): ?>
        <div id="geocomplete"></div>
        <div id="googlemap" style="width:100%;height: 250px;"></div>
        <script>
          $('#geocomplete').geocomplete({
              location: '<?=$this->escapeJs($location->getCoordinates() ?: $location->getAddress());?>',
              map: "#googlemap",
              mapOptions: { zoom: 9 }
          });
        </script>
        <?php endif;?>
    </div>
  </div>
</div>