<?php
if ( ! preg_match('{^UsaRugbyStats\\\\Competition\\\\Form\\\\Fieldset\\\\Competition\\\\Match\\\\MatchTeamEvent\\\\(.*)EventFieldset$}is', get_class($fieldset), $matches) ) {
    return;
}
$canEdit = $this->isGranted('competition.competition.match.team.events.change', @$this->matchTeam);

?>
<tr>
    <td class="column column-minute">
        <?php $element = $fieldset->get('minute'); ?>
        <?php $element->setAttributes(['class' => 'input-sm', 'size' => '1']); ?>
        <?php if ( $canEdit ): ?>
        <?php   echo $this->formElement($element) ?>
        <?php else: ?>
        <?php echo $this->escapeHtml($element->getValue()); ?>
        <?php endif;?>
        <?php echo $this->formElementErrors($element); ?>
    </td>

    <td class="column column-type">
        <?php $element = $fieldset->get('event'); ?>
        <?php echo $this->formHidden($element) ?><?php echo $this->escapeHtml($element->getValue()); ?>
        <?php echo $this->formElementErrors($element); ?>
    </td>

    <td style="padding:0px" class="column column-data">
        <?php echo $this->render('usa-rugby-stats/competition-admin/competition-admin/matches/team/event/' . $fieldset->get('event')->getValue(), $this->vars()); ?>
    </td>

    <td>
        <?php if ( $canEdit ): ?>
        <?php echo $this->formHidden($fieldset->get('id')); ?>
        <a class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-remove competition-match-team-events-removeevent"></i></a>
        <?php endif; ?>
    </td>
</tr>