<?php echo $this->formHidden($fieldset->get('id')); ?>

<div class="panel panel-default competition-match-team competition-match-team-<?= ($type == 'H') ? 'home' : 'away'; ?>">
    <div class="panel-heading">
        <?= ($type == 'H') ? 'Home' : 'Away'; ?> Team
    </div>
    <div class="panel-body">

        <?php echo $this->formHidden($fieldset->get('type')); ?>

        <div class="row form-group">
            <?php $element = $fieldset->get('team'); ?>
            <?php $element->setLabelAttributes(array('class' => 'col-sm-2 control-label')); ?>
            <?php $element->setAttribute('class', 'form-control'); ?>

            <?php echo $this->formLabel($element) ?>
            <div class="col-sm-10">
                <?php echo $this->formElement($element) . $this->formElementErrors($element) ?>
            </div>
        </div>
    </div>

    <table class="table table-striped table-bordered competition-match-team-roster">
        <thead>
            <tr>
                <th>#</th>
                <th>Player</th>
                <th>Position</th>
                <th>FR?</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ( $fieldset->get('players') as $fsPlayer ): ?>
            <?php   if ( !empty($fsPlayer->get('id')->getValue()) ): ?>
            <?php     echo $this->render('usa-rugby-stats/competition-admin/competition-admin/matches/team/player', ['fieldset' => $fsPlayer]); ?>
            <?php   endif; ?>
            <?php endforeach; ?>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="5">
                    <a class="btn btn-sm btn-primary competition-match-team-roster-addplayer" title="Add a Player"><i class="glyphicon glyphicon-plus-sign"></i> Add a Player</a>
                </td>
            </tr>
        </tfoot>
    </table>

    <script type="text/javascript">
        var rosterPlayerTemplate<?=$type?> = '<?php echo $this->escapeJs($this->render('usa-rugby-stats/competition-admin/competition-admin/matches/team/player', ['fieldset' => $fieldset->get('players')->getTemplateElement(), 'isTemplate' => true])); ?>';
        var rosterPlayerIndex<?=$type?> = <?php echo $this->escapeJs(count($fieldset->get('players'))); ?>;

        $(document).on('click', '.competition-match-team-<?= ($type == 'H') ? 'home' : 'away'; ?> .competition-match-team-roster-addplayer', function() {
            var html = rosterPlayerTemplate<?=$type?>.replace(/__playerindex__/g, rosterPlayerIndex<?=$type?>++);
            $('.competition-match-team-<?= ($type == 'H') ? 'home' : 'away'; ?> .competition-match-team-roster tbody').append(html);
        });
        $(document).on('click', '.competition-match-team-<?= ($type == 'H') ? 'home' : 'away'; ?> .competition-match-team-roster-removeplayer', function() {
            $(this).closest('tr').remove();
        });
    </script>

</div>