<?php $this->vars()->matchSideKey = $matchSideKey = $type; ?>

<?php echo $this->formHidden($fieldset->get('id')); ?>

<div class="panel panel-default competition-match-team competition-match-team-<?= ($type == 'H') ? 'home' : 'away'; ?>">
    <div class="panel-heading">
        <?= ($type == 'H') ? 'Home' : 'Away'; ?> Team
    </div>
    <div class="panel-body">

        <?php echo $this->formHidden($fieldset->get('type')); ?>

        <div class="row form-group">
            <?php $element = $fieldset->get('team'); ?>
            <?php $element->setLabelAttributes(array('class' => 'col-sm-2 control-label')); ?>
            <?php $element->setAttribute('class', 'form-control'); ?>

            <?php echo $this->formLabel($element) ?>
            <div class="col-sm-10">
                <?php if ( $this->flags->{"match.teams.$matchSideKey.team"}->is_on() ): ?>
                <?php echo $this->formElement($element) ?>
                <?php else: ?>
                <p class="form-control-static"><?php echo $this->ursTeamLink($element->getValue()); ?></p>
                <?php endif;?>
                <?php echo $this->formElementErrors($element); ?>
            </div>
        </div>

        <?php if ( ! $this->flags->{"match.teams.$matchSideKey.score%visible"}->is_off() ): ?>
        <div class="row form-group">
            <?php $element = $fieldset->get('score'); ?>
            <?php $element->setLabelAttributes(array('class' => 'col-sm-2 control-label')); ?>
            <?php $element->setAttribute('class', 'form-control'); ?>

            <?php echo $this->formLabel($element) ?>
            <div class="col-sm-10">
                <p class="form-control-static"><?php echo $this->escapeHtml($element->getValue()); ?></p>
            </div>
        </div>
        <?php endif; ?>
    </div>

    <?php if ( ! $this->flags->{"match.teams.$matchSideKey.players%visible"}->is_off() ): ?>
    <?php echo $this->render('usa-rugby-stats/competition-admin/competition-admin/matches/team/players', $this->vars()); ?>
    <?php endif; ?>

</div>

<?php echo $this->render('usa-rugby-stats/competition-admin/competition-admin/matches/team/events', $this->vars()); ?>
