<?php $canEdit = $this->flags->{"match.teams.$matchSideKey.players"}->is_on(); ?>

<tr>
    <td class="column column-number" style="text-align:center">
        <?php $element = $fieldset->get('number'); ?>
        <?php if ( $canEdit ): ?>
        <?php echo $this->formElement($element) ?>
        <?php else: ?>
        <?php echo $this->escapeHtml($element->getValue()); ?>
        <?php endif;?>
        <?php echo $this->formElementErrors($element); ?>
    </td>

    <td class="column column-player">
        <?php $element = $fieldset->get('player'); ?>
        <?php if ( $canEdit ): ?>
        <?php echo $this->formElement($element) ?>
        <?php else: ?>
        <?php echo $this->ursPlayerLink($element->getValue()) ?: '--'; ?>
        <?php endif;?>
        <?php echo $this->formElementErrors($element); ?>
    </td>

    <td class="column column-position">
        <?php $element = $fieldset->get('position'); ?>
        <?php $options = $element->getValueOptions(); ?>
        <?php echo $this->escapeHtml(isset($options[$element->getValue()]) ? $options[$element->getValue()] : '???'); ?>
        <?php echo $this->formElementErrors($element); ?>
    </td>

    <td class="column column-isfrontrow" style="text-align:center">
        <?php $element = $fieldset->get('isFrontRow'); ?>
        <?php if ( $canEdit ): ?>
        <?php echo $this->formElement($element) ?>
        <?php else: ?>
        <?php echo $element->getValue() ? '<i class="glyphicon glyphicon-ok"></i>' : ''; ?>
        <?php endif;?>
        <?php echo $this->formElementErrors($element); ?>
    </td>
</tr>