<tr>
    <td class="column column-number">
        <?php $element = $fieldset->get('number'); ?>
        <?php echo $this->formElement($element) . $this->formElementErrors($element); ?>
    </td>

    <td class="column column-player">
        <?php $element = $fieldset->get('player'); ?>
        <?php echo $this->formElement($element) . $this->formElementErrors($element); ?>
    </td>
    
    <td class="column column-position">
        <?php $element = $fieldset->get('position'); ?>
        <?php echo $this->formElement($element) . $this->formElementErrors($element); ?>
    </td>
    
    <td class="column column-isfrontrow">
        <?php $element = $fieldset->get('isFrontRow'); ?>
        <?php echo $this->formElement($element) . $this->formElementErrors($element); ?>
    </td>
    
    <td>
        <?php echo $this->formHidden($fieldset->get('id')); ?>
        <a class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-remove competition-match-team-roster-removeplayer"></i></a>
    </td>
</tr>