<?php $canEdit = $this->flags->{"match.teams.$matchSideKey.players"}->is_on(); ?>
<tr>
    <td class="column column-number">
        <?php $element = $fieldset->get('number'); ?>
        <?php if ( $canEdit ): ?>
        <?php echo $this->formElement($element) ?>
        <?php else: ?>
        <?php echo $this->escapeHtml($element->getValue()); ?>
        <?php endif;?>
        <?php echo $this->formElementErrors($element); ?>
    </td>

    <td class="column column-player">
        <?php $element = $fieldset->get('player'); ?>
        <?php if ( $canEdit ): ?>
        <?php echo $this->formElement($element) ?>
        <?php else: ?>
        <?php echo $this->escapeHtml($element->getValue()); ?>
        <?php endif;?>
        <?php echo $this->formElementErrors($element); ?>
    </td>

    <td class="column column-position">
        <?php $element = $fieldset->get('position'); ?>
        <?php if ( $canEdit ): ?>
        <?php echo $this->formElement($element) ?>
        <?php else: ?>
        <?php echo $this->escapeHtml($element->getValue()); ?>
        <?php endif;?>
        <?php echo $this->formElementErrors($element); ?>
    </td>

    <td class="column column-isfrontrow">
        <?php $element = $fieldset->get('isFrontRow'); ?>
        <?php if ( $canEdit ): ?>
        <?php echo $this->formElement($element) ?>
        <?php else: ?>
        <?php echo $this->escapeHtml($element->getValue()); ?>
        <?php endif;?>
        <?php echo $this->formElementErrors($element); ?>
    </td>

    <td>
        <?php if ( $canEdit ): ?>
        <?php echo $this->formHidden($fieldset->get('id')); ?>
        <a class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-remove competition-match-team-roster-removeplayer"></i></a>
        <?php endif; ?>
    </td>
</tr>