<?php $canEdit = $this->flags->{"match.teams.$matchSideKey.players"}->is_on(); ?>
<?php $argv = $this->vars()->getArrayCopy(); ?>

<table class="table table-striped table-bordered competition-match-team-roster">
    <thead>
        <tr>
            <th style="text-align:center">#</th>
            <th>Player</th>
            <th>Position</th>
            <th style="text-align:center">FR?</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ( $fieldset->get('players') as $fsPlayer ): ?>
        <?php   echo $this->render('usa-rugby-stats/competition-admin/competition-admin/matches/team/player', array_merge($argv, ['fieldset' => $fsPlayer])); ?>
        <?php endforeach; ?>
    </tbody>
</table>