<?php
$getters = array();
foreach ($this->userlistElements as $element) {
    $parts = explode('_', $element);
    array_walk($parts, function (&$val) {
        $val = ucfirst($val);
    });
    $getters[$element] = 'get' . implode('', $parts);
}
?>

<h1><?php echo $this->translate('Account Search Results') ?></h1>

<div class="filter-bar" style="margin-bottom: 25px">
    <div class="row">
        <div class="col-sm-6">
            <div class="row">
                <form role="form" method="GET" action="<?php echo $this->url('zfcadmin/zfcuseradmin/search') ?>">
                  <div class="col-xs-10">
                    <input name="q" type="search" class="form-control" id="userSearch" placeholder="Enter fragment of username, real name or email address...">
                  </div>
                  <div class="col-xs-2" style="padding-left:0"><button type="submit" class="btn btn-default">Search</button></div>
                </form>
            </div>
        </div>
        <div class="col-sm-4"></div>
        <div class="col-xs-2">
            <a href="<?php echo $this->url('zfcadmin/zfcuseradmin/create') ?>" class="btn btn-primary">
                <i class="glyphicon glyphicon-plus"></i> <?php echo $this->translate('Add New User') ?>
            </a>
        </div>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <?php foreach ($this->userlistElements as $name => $element): ?>
                <th><?php echo $this->escapeHtml($name ? : $element); ?></th>
            <?php endforeach; ?>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($this->users as $user): ?>
        <tr>
            <?php foreach ($this->userlistElements as $element): ?>
                <td class="cell cell-<?php echo $this->escapeHtml($element) ?>">
                    <?php $parts = explode('_', $element); ?>
                    <?php echo call_user_func(array($user, $getters[$element])); ?>
                </td>
            <?php endforeach; ?>
            <td class="cell cell-ctrls">
                <a href="<?php echo $this->url('zfcadmin/zfcuseradmin/edit', array('userId' => $user->getId())); ?>">
                    <?php echo $this->translate('Edit') ?>
                </a>
                |
                <a href="<?php echo $this->url('zfcadmin/zfcuseradmin/remove', array('userId' => $user->getId())); ?>"
                   onclick="return confirm('<?php echo $this->translate('Really delete user?') ?>')">
                    <?php echo $this->translate('Delete') ?>
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
    <tfoot>
    <tr>
        <td colspan="<?php echo count($this->userlistElements) + 1; ?>">
            <?php echo $this->paginationControl($this->users, 'Sliding', 'usa-rugby-stats/account-admin/account-search/pagination', ['q' => $q]); ?>
        </td>
    </tr>
    </tfoot>
</table>
