<div class="row">
    <div class="col-sm-5">
        <div class="row form-group">
            <div class="col-sm-4 control-label">Type</div>
            <div class="col-sm-8">
                <p class="form-control-static"><?php echo $this->escapeHtml($competition->getTypeString()); ?></p>
            </div>
        </div>

        <div class="row form-group">
            <div class="col-sm-4 control-label">Variant</div>
            <div class="col-sm-8">
                <p class="form-control-static"><?php echo $this->escapeHtml($competition->getVariant()); ?></p>
            </div>
        </div>

        <div class="row form-group">
            <div class="col-sm-4 control-label"># Divisions</div>
            <div class="col-sm-8">
                <p class="form-control-static"><?php echo $this->escapeHtml(count($competition->getDivisions())); ?></p>
            </div>
        </div>

        <div class="row form-group">
            <div class="col-sm-4 control-label"># Teams</div>
            <div class="col-sm-8">
                <p class="form-control-static"><?php echo $this->escapeHtml(count($competition->getTeamMemberships())); ?></p>
            </div>
        </div>

        <div class="row form-group">
            <div class="col-sm-4 control-label"># Matches</div>
            <div class="col-sm-8">
                <p class="form-control-static"><?php echo $this->escapeHtml(count($competition->getMatches())); ?></p>
            </div>
        </div>
    </div>
</div>