<div class="page-header">
  <?php if ( $this->isGranted('competition-frontend.competition.update', $competition) ):?>
  <div class="pull-right" style="margin-top:5px">
    <a class="btn btn-primary" href="<?=$this->url('usarugbystats_frontend_competition/update', ['id' => $competition->getId()]); ?>"><i class="glyphicon glyphglyphicon glyphicon-cog"></i> Edit Competition</a>
  </div>
  <?php endif; ?>
  <h1><?=$this->escapeHtml($competition->getName()); ?></h1>
</div>

<?php
$divisions = $competition->getDivisions();
$tableStructure = [];
$tableRowCount = 0;
foreach ( $divisions as $division) {
    $tableStructure[$division->getId()] = $division->getTeamMemberships()->toArray();
    $tableRowCount = max($tableRowCount, count($tableStructure[$division->getId()]));
}
?>

<div class="panel panel-default">
  <div class="panel-heading">Participating Teams</div>
  <?php if (count($divisions)): ?>
  <table class="table" id="sort">
    <thead>
      <tr>
        <?php foreach ( $divisions as $division): ?>
        <th><?=$this->escapeHtml($division->getName()); ?></th>
        <?php endforeach; ?>
      </tr>
    </thead>
    <tbody>
      <?php for ( $i = 0; $i < $tableRowCount; $i++ ): ?>
      <tr>
        <?php foreach ( $divisions as $division): ?>
        <?php   $teamMembership = @$tableStructure[$division->getId()][$i] ?: NULL ?>
        <td>
          <?php if ( ! is_null($teamMembership) ): ?>
          <a href="<?=$this->url('usarugbystats_frontend_team', ['id' => $teamMembership->getTeam()->getId()]); ?>">
            <?=$this->escapeHtml($teamMembership->getTeam()->getName()) ?>
          </a>
          <?php endif; ?>
        </td>
        <?php endforeach; ?>
      </tr>
      <?php endfor; ?>
    </tbody>
  </table>

  <?php else: ?>
  <div class="panel-body">
    <div class="pull-center">There are no divisions in this competition.</div>
  </div>
  <?php endif; ?>
</div>


<?php $matches = $competition->getMatches(); ?>
<div class="panel panel-default">
  <div class="panel-heading">Competition Games</div>
  <?php if (count($matches)): ?>
  <?php   echo $this->render('usa-rugby-stats/competition-frontend/partials/games-listing', ['matches' => $matches, 'showScore' => true]); ?>
  <?php else: ?>
  <div class="panel-body">
    <div class="pull-center">This team is not participating in any competitions.</div>
  </div>
  <?php endif; ?>
</div>
