<div class="page-header">
  <?php if ( $this->isGranted('competition.competition.update', $competition) ):?>
  <div class="pull-right" style="margin-top:5px">
    <a class="btn btn-primary" href="<?=$this->url('usarugbystats_frontend_competition/update-details', ['id' => $competition->getId()]); ?>"><i class="glyphicon glyphglyphicon glyphicon-cog"></i> Edit Competition</a>
  </div>
  <?php endif; ?>
  <h1><?=$this->escapeHtml($competition->getName()); ?></h1>
</div>

<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
  <li class="active"><a href="#details" role="tab" data-toggle="tab">Details</a></li>
  <li><a href="#standings" role="tab" data-toggle="tab">Standings</a></li>
  <li><a href="#divisions" role="tab" data-toggle="tab">Divisions</a></li>
  <li><a href="#matches" role="tab" data-toggle="tab">Matches</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
  <div class="tab-pane active" id="details" style="padding: 20px"><?php echo $this->render('usa-rugby-stats/competition-frontend/competition/details.phtml', $this->vars()); ?></div>
  <div class="tab-pane" id="standings" style="padding: 20px"><?php echo $this->render('usa-rugby-stats/competition-frontend/competition/standings.phtml', $this->vars()); ?></div>
  <div class="tab-pane" id="divisions" style="padding: 20px"><?php echo $this->render('usa-rugby-stats/competition-frontend/competition/teamlisting.phtml', $this->vars()); ?></div>
  <div class="tab-pane" id="matches" style="padding: 20px"><?php echo $this->render('usa-rugby-stats/competition-frontend/competition/matchlisting.phtml', $this->vars()); ?></div>
</div>
