<div style="margin-bottom: 20px">
    <ul class="nav nav-pills">
        <li<?=($page == 'details' ? ' class="active"' : ''); ?>><a href="<?=$this->url('usarugbystats_frontend_competition',['id' => $entity->getId()]) ?>">Competition</a></li>
        <li<?=($page == 'update' ? ' class="active"' : ''); ?>><a href="<?=$this->url('usarugbystats_frontend_competition/update-details',['id' => $entity->getId()]) ?>">Edit Details</a></li>
        <li<?=($page == 'matches' ? ' class="active"' : ''); ?>><a href="<?=$this->url('usarugbystats_frontend_competition/update-matches',['id' => $entity->getId()]) ?>">Manage Matches</a></li>
    </ul>
</div>