<?php if (isset($standings['by-division']) && count($standings['by-division'])):?>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th></th>
            <th>GP</th>
            <th>W</th>
            <th>L</th>
            <th>T</th>
            <th>PF</th>
            <th>PA</th>
            <th>PD</th>
            <th>BT</th>
            <th>BL</th>
            <th>FF</th>
            <th>PTS</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ( $standings['by-division'] as $divkey => $divdata ): ?>
        <tr>
            <th colspan="13" style="font-size:1.2em; background-color: #fcf8e3 !important;"><?php echo $this->escapeHtml($this->ursCompetitionDivisionName($divdata['division'])); ?></th>
        </tr>
    <?php foreach ( $divdata['standings'] as $entry ): ?>
    <?php   $entry instanceof UsaRugbyStats\Competition\Entity\Competition\TeamRecord; ?>
        <tr>
            <td><strong><?php echo $this->ursTeamLink($entry->getTeam()); ?></strong></td>
            <td><?php echo $this->escapeHtml($entry->getTotalGames()); ?></td>
            <td><?php echo $this->escapeHtml($entry->getTotalWins()); ?></td>
            <td><?php echo $this->escapeHtml($entry->getTotalLosses()); ?></td>
            <td><?php echo $this->escapeHtml($entry->getTotalTies()); ?></td>
            <td><?php echo $this->escapeHtml($entry->getScoreInFavor()); ?></td>
            <td><?php echo $this->escapeHtml($entry->getScoreAgainst()); ?></td>
            <td><?php echo $this->escapeHtml($entry->getScoreDifferential()); ?></td>
            <td><?php echo $this->escapeHtml($entry->getTryBonuses()); ?></td>
            <td><?php echo $this->escapeHtml($entry->getLossBonuses()); ?></td>
            <td><?php echo $this->escapeHtml($entry->getForfeits()); ?></td>
            <td><?php echo $this->escapeHtml($entry->getTotalPoints()); ?></td>
        </tr>
    <?php endforeach; ?>
    <?php endforeach; ?>
    </tbody>
</table>

<div class="well well-small" style="font-size: 11px">
<b>GP</b> = Games Played; <b>W</b> = Wins; <b>L</b> = Losses; <b>T</b> = Ties; <b>PF</b> = Points For; <b>PA</b> = Points Against; <b>PD</b> = Points Differential; <b>BT</b> = Try Bonus (4 Tries or More); <b>BL</b> = Loss Bonus (Loss by 7 or Less); <b>FF</b> = Forfeit Deduction; <b>PTS</b> = League Points
</div>

<?php endif; ?>