<?php
$divisions = $competition->getDivisions();
$tableStructure = [];
$tableRowCount = 0;
foreach ( $divisions as $division) {
    $tableStructure[$division->getId()] = $division->getTeamMemberships()->toArray();
    $tableRowCount = max($tableRowCount, count($tableStructure[$division->getId()]));
}
?>

  <?php if (count($divisions)): ?>
  <table class="table" id="sort">
    <?php if (count($divisions) > 1):?>
    <thead>
      <tr>
        <?php foreach ( $divisions as $division): ?>
        <th><?=$this->escapeHtml($division->getName()); ?></th>
        <?php endforeach; ?>
      </tr>
    </thead>
    <?php endif; ?>
    <tbody>
      <?php for ( $i = 0; $i < $tableRowCount; $i++ ): ?>
      <tr>
        <?php foreach ( $divisions as $division): ?>
        <?php   $teamMembership = @$tableStructure[$division->getId()][$i] ?: NULL ?>
        <td>
          <?php if ( ! is_null($teamMembership) ): ?>
          <img src="<?=$this->escapeHtmlAttr($this->ursTeamLogoUrl($teamMembership->getTeam()));?>" /> <?=$this->ursTeamLink($teamMembership->getTeam()); ?>
          <?php endif; ?>
        </td>
        <?php endforeach; ?>
      </tr>
      <?php endfor; ?>
    </tbody>
  </table>

  <?php else: ?>
  <div class="panel-body">
    <div class="pull-center">There are no divisions in this competition.</div>
  </div>
  <?php endif; ?>
