<h1><?php echo $this->escapeHtml($entity->getName()); ?></h1>

<?php echo $this->render('usa-rugby-stats/competition-frontend/competition/navigation', ['page' => 'update', 'entity' => $entity]); ?>

<?php
$form->setAttribute('class', 'form-horizontal');
$form->prepare();

echo $this->form()->openTag($form);

$submitButton = $form->get('submit');
$submitButton->setAttribute('class', 'btn btn-lg btn-success');

?>

<div class="row">
    <div class="col-md-8">
        <?php echo $this->render('usa-rugby-stats/competition-admin/competition-admin/form', $this->vars()); ?>
        <?php echo $this->render('usa-rugby-stats/competition-admin/competition-admin/form/divisions', ['fieldset' => $form->get('competition')]); ?>
    </div>
</div>

<div class="clearfix"></div>
<div class="pull-left"><?php echo $this->formButton($submitButton); ?></div>

<?php echo $this->form()->closeTag() ?>