<h1><?php echo $this->escapeHtml($competition->getName()); ?></h1>

<?php

$canEdit = $this->isGranted('competition.competition.update.details', @$competition) || $this->isGranted('competition.competition.update.divisions', @$competition);
if ( $canEdit ) {
    $form->setAttribute('class', 'form-horizontal');
    $form->prepare();

    echo $this->form()->openTag($form);

    $submitButton = $form->get('submit');
    $submitButton->setAttribute('class', 'btn btn-lg btn-success');
}

?>

<div class="row">
    <div class="col-md-6">
        <?php echo $this->render('usa-rugby-stats/competition-admin/competition-admin/form', $this->vars()); ?>
    </div>
    <div class="col-md-6">
        <?php echo $this->render('usa-rugby-stats/competition-admin/competition-admin/form/divisions', ['competition' => @$competition, 'fieldset' => $form->get('competition'), 'teamViewRoute' => 'usarugbystats_frontend_team']); ?>
    </div>
</div>

<?php if ( $canEdit ): ?>
<div class="clearfix"></div>
<div class="pull-left"><?php echo $this->formButton($submitButton); ?></div>

<?php echo $this->form()->closeTag() ?>
<?php endif; ?>