<?php $form->setAttribute('class', 'form-horizontal'); ?>
<?php echo $this->form()->openTag($form) ?>

<?php $submitButton = $form->get('submit'); ?>
<?php $submitButton->setAttribute('class', 'btn btn-lg btn-success'); ?>

<div class="row">
    <div class="col-md-6">
    
        <?php $fieldset = $form->get('union'); ?>
        
        <?php echo $this->formHidden($fieldset->get('id')); ?>
        
        <div class="panel panel-default">
            <div class="panel-heading">Union Details</div>
            <div class="panel-body">

                <div class="row form-group">
                    <?php $element = $fieldset->get('name'); ?>
                    <?php $element->setLabelAttributes(array('class' => 'col-sm-4 control-label')); ?>
                    <?php $element->setAttribute('class', 'form-control'); ?>
                    
                    <?php echo $this->formLabel($element) ?>
                    <div class="col-sm-8">
                        <?php echo $this->formElement($element) . $this->formElementErrors($element) ?>
                    </div>
                </div>

            </div>
        </div>
    </div>
    
</div>
<div class="clearfix"></div>
<div class="pull-left"><?php echo $this->formButton($submitButton); ?></div>

<?php if ($this->redirect): ?>
    <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>">
<?php endif ?>
<?php echo $this->form()->closeTag() ?>