<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <?php echo $this->headTitle($this->translate('USA Rugby Stats'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->setCharset('utf-8')
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Stylesheets -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/favicon.ico'))
                        ->appendStylesheet($this->basePath() . '/assets/css/vendor/bootstrap.min.css')
                        ->appendStylesheet($this->basePath() . '/assets/css/vendor/select2.css')
                        ->appendStylesheet($this->basePath() . '/assets/css/vendor/select2-bootstrap.css')
                        ->appendStylesheet($this->basePath() . '/assets/css/vendor/bootstrap-datetimepicker.min.css')
                        ->appendStylesheet($this->basePath() . '/assets/css/bs3override.css')
                        ->appendStylesheet($this->basePath() . '/assets/css/style.css')
        ; ?>

        <!-- Fonts -->
        <script type="text/javascript" src="//use.typekit.net/dqm3mdr.js"></script>
        <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
        <script type="text/javascript">var USARugbyStats = {};</script>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                  ->appendFile('//oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
                  ->appendFile('//oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                  ->appendFile($this->basePath() . '/assets/js/vendor/jquery.min.js')
                  ->appendFile($this->basePath() . '/assets/js/vendor/bootstrap.min.js')
                  ->appendFile($this->basePath() . '/assets/js/vendor/moment.js')
                  ->appendFile($this->basePath() . '/assets/js/vendor/bootstrap-datetimepicker.min.js')
                  ->appendFile($this->basePath() . '/assets/js/vendor/select2.js')
                  ->appendFile('//maps.googleapis.com/maps/api/js?libraries=places')
                  ->appendFile($this->basePath() . '/assets/js/vendor/jquery.geocomplete.min.js')
                  ->appendFile($this->basePath() . '/assets/js/min/main-min.js')
             ;
        ?>

    </head>
    <body>

        <div class="container"<?=empty($this->containerAttributes) ? '' : ' ' . implode(' ', $this->containerAttributes); ?>>

            <header>

                <div id="brand">
                    <a href="<?php echo $this->url('home'); ?>">USA Rugby CMS</a>
                </div>

                <div id="search-box" style="display:none">
                    <span class="icon-search"></span><input id="search" type="text" placeholder="Search" />
                </div>

                <div class="pull-right" id="comps">
                    <a id="drawer"></span>Competitions Menu
                        <span class="line line-1"></span>
                        <span class="line line-2"></span>
                        <span class="line line-3"></span>
                    </a>

                </div>

                <?php if ( $this->plugin('user')->isAuthenticated() ): ?>
                <div class="dropdown pull-right" id="user">
                    <a data-toggle="dropdown">
                        <?php echo $this->gravatar($this->user()->getEmail())->getImgTag(); ?>
                        <?php echo $this->escapeHtml($this->user()->getDisplayName()); ?>
                    </a>

                    <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                        <li><a role="menuitem" tabindex="-1" href="<?php echo $this->url('ldc-user-profile'); ?>">Your Profile</a></li>
                        <li><a role="menuitem" tabindex="-1" href="<?php echo $this->url('zfcuser/logout'); ?>">Logout</a></li>
                    </ul>
                </div>
                <?php else: ?>
                <div class="pull-right" id="user">
                    <a href="<?php echo $this->url('zfcuser/login'); ?>">Sign In</a>
                </div>
                <?php endif; ?>

            </header>

            <div id="drawer-menu">
                <ul>

<?php if ($this->user()->hasRole('team_admin')): ?>
<?php   $teams = $this->user()->getRoleAssignment('team_admin')->getManagedTeams(); ?>
<?php   if ( count($teams) > 0 ): ?>
                  <li><a style="font-weight:bold" href="<?=$this->url('usarugbystats_frontend_dashboard/team-admin'); ?>">Teams</a></li>
<?php     foreach ( $teams as $team ): ?>
                  <li><a title="<?php echo $this->escapeHtmlAttr($team->getName()); ?>" style="overflow:hidden" href="<?=$this->url('usarugbystats_frontend_team', ['id' => $team->getId()]); ?>">&mdash; <?php echo $this->escapeHtml($team->getName()); ?></a></li>
<?php     endforeach; ?>
<?php   endif;?>
<?php endif;?>

<?php if ($this->user()->hasRole('union_admin')): ?>
<?php   $unions = $this->user()->getRoleAssignment('union_admin')->getManagedUnions(); ?>
<?php   if ( count($unions) > 0 ): ?>
                  <li><a style="font-weight:bold"href="<?=$this->url('usarugbystats_frontend_dashboard/union-admin'); ?>">Unions</a></li>
<?php     foreach ( $unions as $union ): ?>
                  <li><a title="<?php echo $this->escapeHtmlAttr($union->getName()); ?>" style="overflow:hidden" href="<?=$this->url('usarugbystats_frontend_union', ['id' => $union->getId()]); ?>">&mdash; <?php echo $this->escapeHtml($union->getName()); ?></a></li>
<?php     endforeach; ?>
<?php   endif;?>
<?php endif;?>

<?php if ($this->user()->hasRole('competition_admin')): ?>
<?php   $competitions = $this->user()->getRoleAssignment('competition_admin')->getManagedCompetitions(); ?>
<?php   if ( count($competitions) > 0 ): ?>
                  <li><a style="font-weight:bold" href="<?=$this->url('usarugbystats_frontend_dashboard/competition-admin'); ?>">Competitions</a></li>
<?php     foreach ( $competitions as $competition ): ?>
                  <li><a title="<?php echo $this->escapeHtmlAttr($competition->getName()); ?>" style="overflow:hidden" href="<?=$this->url('usarugbystats_frontend_competition', ['id' => $competition->getId()]); ?>">&mdash; <?php echo $this->escapeHtml($competition->getName()); ?></a></li>
<?php     endforeach; ?>
<?php   endif;?>
<?php endif;?>

                  <li><a style="font-weight:bold" href="#">Support</a></li>
              	  <li><a href="https://usarugby.zendesk.com/forums/22264177-Competition-Management-System" target="_blank">&mdash; Support Center</a></li>
               	  <li><a href="https://usarugby.zendesk.com/anonymous_requests/new" target="_blank">&mdash; Contact</a></li>

                <?php if ($this->user()->hasRole('super_admin')): ?>
                  <li><a style="font-weight:bold" href="<?php echo $this->escapeHtmlAttr($this->url('zfcadmin')); ?>">Admin Panel</a></li>
                  <?php echo $this->navigation('admin_navigation')
                                  ->menu()
                                  ->setUlClass('admin-navigation')
                                  ->setMaxDepth(0)
                                  ->setRenderInvisible(false)?>
                <?php endif; ?>
                </ul>

            </div>

            <div id="inner">

                <?php if ( isset($this->cover) ): ?>
                <?php echo $this->render($this->cover, $this->coverVars ?: $this->vars()); ?>
                <?php endif; ?>

                <main class="row<?=empty($this->mainClasses) ? '' : ' ' . implode(' ', $this->mainClasses); ?>">
                    <?php
                    // Render different levels of FlashMessenger messages in a Bootstrap3-friendly way
                    $flash = $this->flashMessenger();
                    $flash->setMessageOpenFormat('<div%s>
                         <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                             &times;
                         </button>
                         <ul><li>')
                         ->setMessageSeparatorString('</li><li>')
                         ->setMessageCloseString('</li></ul></div>');

                    echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
                    echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
                    echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
                    echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
                    ?>

                    <?php echo $this->content; ?>
                </main>

                <footer>
                    <div class="row">
                        <div class="col-lg-12">
                            <p>Copyright &copy; 2014 USA Rugby</p>
                        </div>
                    </div>
                </footer>

            </div>
        </div>

        <?php echo $this->inlineScript(); ?>
    </body>
</html>
