<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('USA Rugby Stats'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>
                        
        <link href="/assets/css/vendor/datepicker.css" rel="stylesheet" type="text/css">
        <link href="/assets/css/vendor/chosen.css" rel="stylesheet" type="text/css">
        <link href="/assets/css/app.css" rel="stylesheet" type="text/css">
        <link href="/assets/css/style.css" rel="stylesheet" type="text/css"> 
        <link href="/assets/css/print.css" media="print" rel="stylesheet" type="text/css">

        <!-- Fonts -->
        <script type="text/javascript" src="//use.typekit.net/dqm3mdr.js"></script>
        <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
        
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
        
        <script src="/assets/js/vendor/bootstrap-datepicker.js" type="text/javascript"></script>
        <script src="/assets/js/vendor/chosen.jquery.min.js" type="text/javascript"></script>
        <script src="/assets/js/vendor/jquery.dataTables.js" type="text/javascript"></script>
        <script src="/assets/js/vendor/jquery.timeentry.pack.js" type='text/javascript'></script>
        <script src="/assets/js/vendor/jquery.dataTables.yadcf.js" type='text/javascript'></script>
        <script src="/assets/js/vendor/intro.js" type="text/javascript"></script>
        <script src="http://maps.googleapis.com/maps/api/js?sensor=false&amp;libraries=places"></script>
        <script src="/assets/js/vendor/jquery.geocomplete.js"></script>
        
<?php if (!empty($this->iframe)) { ?>
  <script src='https://www.allplayers.com/iframe.js?usar_stats' type='text/javascript'></script>
<?php } ?>
        
    </head>
    <body<?php echo empty($this->iframe) ? '' : ' class="app"'; ?>>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="http://usarugby.org/images/usarugby-2x-logo-beta.png" /></a>
                </div>

                <ul class="nav navbar-nav navbar-right">

                <?php if ($this->user()->hasRole('super_admin')): ?>
                  <li class = "dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin Options <b class = "caret"></b></a>
                      <ul class = "dropdown-menu">
                          <!-- <li><a href='db_update.php'>Update Player Database</a></li> -->
                          <!-- <li><a href='db_update_team.php'>Add Club to Club Database</a></li> -->
                          <li><a href='users.php'>User Management</a></li>
                          <li><a href='groups_active.php'>Group Management</a></li>
                          <li class="divider"></li>
                          <li class="dropdown-submenu">
                            <a tabindex="-1" href="processqueue">Sync (<?php $qh = new Source\QueueHelper(); echo $qh->Queue()->count();?>)</a>
                            <ul class="dropdown-menu">
                              <li><a href='db_update_users_process.php'>Users</a></li>
                              <li><a href='groups_sync.php'>Groups</a></li>
                              <li><a href='group_members_sync.php'>Players in Groups</a></li>
                            </ul>
                          </li>
                      </ul>
                  </li>
                <?php endif; ?>
                
                <?php if ( $this->zfcUserIdentity() ): ?>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <?php echo $this->zfcUserDisplayName(); ?> <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li class="divider"></li>
                      <li><a href="<?php echo $this->url('zfcuser'); ?>">Account</a></li>
                      <li><a href="<?php echo $this->url('zfcuser/logout'); ?>">Logout</a></li>
                    </ul>
                  </li>
                <?php else: ?>
                  <li><a href="<?php echo $this->url('zfcuser/login'); ?>">Sign In</a></li>
                <?php endif; ?>
                </ul>
                

                <?php echo $this->navigation('default')
                                ->menu()
                                ->setUlClass('nav navbar-nav navbar-right')
                                ->setMaxDepth(0)
                                ->setRenderInvisible(false)?>
                
            </div>
        </nav>
        <div class="container">
        
<?php
if (isset($_SESSION['alert_message'])) {
	$alert = $_SESSION['alert_message'];
    unset($_SESSION['alert_message']);
    // @TODO: support alert types {info, success, error}.
    echo '<div class="alert alert-info">' . $alert . '</div>';
}
?>        
        
            <?php echo $this->content; ?>

        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
