<?php $isTemplate = @$isTemplate == true; ?>
<?php $elId = $fieldset->get('id'); ?>
<?php $elAccount = $fieldset->get('account'); ?>
<?php $elIdValue = $elId->getValue(); ?>

<tr data-recordid="<?php echo $this->escapeHtmlAttr($elId->getValue()); ?>">
    <?php echo $this->formElement($elId); ?>
    <?php echo $this->formElementErrors($elId); ?>

    <td class="column column-name">
        <?php $elAccount->setAttribute('class', 'form-control input-sm'); ?>
        <?php echo $this->formElement($elAccount); ?>
        <?php echo $this->formElementErrors($elAccount); ?>
    </td>

    <td class="col-sm-2 column column-actions" style="text-align:right; padding-right: 15px;"><a class="btn btn-xs btn-danger dropadmin" title="Remove Administrator"><i class="glyphicon glyphicon-trash"></i></a></td>
</tr>