<h1>Unions</h1>

<div class="filter-bar" style="margin-bottom: 25px">
    <div class="row">
        <div class="col-sm-6">
            <div class="row">
                <form role="form" method="GET" action="<?php echo $this->url('zfcadmin/usarugbystats_unionadmin/search') ?>">
                  <div class="col-xs-10">
                    <input name="q" type="search" class="form-control" id="userSearch" placeholder="Enter fragment of union name" value="<?=$this->escapeHtmlAttr($this->q);?>">
                  </div>
                  <div class="col-xs-2" style="padding-left:0"><button type="submit" class="btn btn-default">Search</button></div>
                </form>
            </div>
        </div>
        <div class="col-sm-4"></div>
        <div class="col-xs-2">
            <a class="btn btn-large btn-primary pull-right" href="<?php echo $this->url('zfcadmin/usarugbystats_unionadmin/create'); ?>">
                <i class="glyphicon glyphicon-plus"></i> Add New Union
            </a>
        </div>
    </div>
</div>

<?php if ($this->paginator->count() == 0 ): ?>
<div class="alert alert-warning">There are no unions!</div>
<?php endif; ?>

<?php if ($this->paginator->count() > 0 ): ?>
<table class="table table-striped">
    <thead>
        <tr>
            <th><?php echo $this->translate('ID') ?></th>
            <th><?php echo $this->translate('Name') ?></th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($this->paginator as $entity): ?>
        <tr>
            <td class="cell cell-id" style="width:50px">
                <?php echo $this->escapeHtml($entity->getId()); ?>
            </td>
            <td class="cell cell-name">
                <?php echo $this->escapeHtml($entity->getName()); ?>
            </td>
            <td class="col-sm-2 cell cell-ctrls" style="text-align:right">
                <a href="<?php echo $this->url('zfcadmin/usarugbystats_unionadmin/edit', array('id' => $entity->getId())); ?>">
                    <?php echo $this->translate('Edit') ?>
                </a>
                |
                <a href="<?php echo $this->url('zfcadmin/usarugbystats_unionadmin/remove', array('id' => $entity->getId())); ?>">
                    <?php echo $this->translate('Delete') ?>
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">
                <?php echo $this->paginationControl($this->users, 'Sliding', 'usa-rugby-stats/competition-admin/union-admin/search/pagination', ['q' => $q]); ?>
            </td>
        </tr>
    </tfoot>
</table>
<?php endif; ?>