<h1><?php echo $this->translate('Your Profile'); ?></h1>

<?php
if (!$this->options->isEnabled()) {
    echo $this->translate('Profile page is disabled');
    return;
}
$form = $this->profileForm;
$form->prepare();
$form->setAttribute('action', $this->url('ldc-user-profile'));
$form->setAttribute('method', 'post');

$validationGroup = $form->getValidationGroup();
?>

<?php echo $this->form()->openTag($form) ?>

    <div class="row">
        <div class="col-sm-6">
            <?php echo $this->render('ldc-user-profile/profile/extension/' . $form->get('zfcuser')->getName(), array('validationGroup' => @$validationGroup['zfcuser'], 'fieldset' => $form->get('zfcuser'))); ?>
        </div>
        <div class="col-sm-6">
            <?php echo $this->render('ldc-user-profile/profile/extension/' . $form->get('extprofile')->getName(), array('validationGroup' => @$validationGroup['extprofile'], 'fieldset' => $form->get('extprofile'))); ?>
            <?php echo $this->render('ldc-user-profile/profile/extension/' . $form->get('personalstats')->getName(), array('validationGroup' => @$validationGroup['personalstats'], 'fieldset' => $form->get('personalstats'))); ?>
        </div>
    </div>

    <?php foreach ($form->getElements() as $element): ?>
        <?php if (!$element instanceof Zend\Form\Element\Button && !$element instanceof Zend\Form\Element\Hidden): ?>
            <dt><?php echo $this->formLabel($element) ?></dt>
        <?php endif ?>
        <?php if ($element instanceof Zend\Form\Element\Button): ?>
        <?php   $element->setAttribute('class', 'btn btn-lg btn-primary'); ?>
            <dd><?php echo $this->formButton($element) ?></dd>
        <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
            <dd><?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?></dd>
        <?php else: ?>
            <dd><?php echo $this->formInput($element) . $this->formElementErrors($element) ?></dd>
        <?php endif ?>
    <?php endforeach;?>

    </dl>
<?php echo $this->form()->closeTag() ?>