<div class="rbac-assignment rbac-assignment-member panel panel-default" data-type="member" data-index="<?php echo $this->escapeHtmlAttr($index); ?>">
    <div class="panel-heading">
        Member
        <div class="pull-right">
            <a class="btn btn-xs btn-danger rbac-assignment-delete"><i class="glyphicon glyphicon-trash"></i></a>
        </div>
    </div>

    <?php echo $this->render('usa-rugby-stats/account-admin/role-assignments/common', array('fieldset' => $fieldset)); ?>

</div>