<?php 
$this->fieldset->get('type')->setValue($this->type);
foreach ( $this->fieldset as $item ) {
    $item->setLabelAttributes(array('class' => 'col-md-2 control-label'));
    $item->setAttributes(array('class' => 'form-control'));
}
?>

<div class="rbac-assignment panel panel-default" data-index="<?php echo $this->escapeHtmlAttr($index); ?>">
    <div class="panel-heading">
        Super Administrator
        <div class="pull-right">
            <a class="btn btn-xs btn-danger rbac-assignment-delete"><i class="glyphicon glyphicon-trash"></i></a>
        </div>
    </div>

    <?php echo $this->render('usa-rugby-stats/account-admin/role-assignments/common', array('fieldset' => $fieldset)); ?>

</div>