<?php
use UsaRugbyStats\Competition\Entity\Team;

foreach ( $this->fieldset as $item ) {
    $item->setLabelAttributes(array('class' => 'col-md-2 control-label'));
    $item->setAttributes(array('class' => 'form-control'));
}

$managedTeamTemplate = function($view, $element, $team = null, $isTemplate = false)
{
    $teamId = $view->escapeHtmlAttr($element->getValue());
    $hiddenElement = $isTemplate ? $view->formSelect($element) : $view->formHidden($element);
    $teamName = $view->escapeHtml(( $team instanceof Team ) ? $team->getName() : (string)$team);

    return <<<EOB
            <tr data-teamid="{$teamId}">
                <td>
                    {$hiddenElement}
                    {$teamName}
                </td>
                <td class="col-sm-2" style="text-align:right"><a class="btn btn-xs btn-danger dropteam" title="Remove Team"><i class="glyphicon glyphicon-trash"></i></a></td>
            </tr>
EOB;
}

?>

<div class="rbac-assignment rbac-assignment-teamadmin panel panel-default" data-index="<?php echo $this->escapeHtmlAttr($index); ?>">
    <div class="panel-heading">
        Team Administrator
        <div class="pull-right">
            <a class="btn btn-xs btn-success rbac-assignment-addteam" title="Add Team"><i class="glyphicon glyphicon-plus-sign"></i></a>
            <a class="btn btn-xs btn-danger rbac-assignment-delete" title="Remove Role Assignment"><i class="glyphicon glyphicon-trash"></i></a>
        </div>
    </div>

    <?php echo $this->render('usa-rugby-stats/account-admin/role-assignments/common', array('fieldset' => $fieldset)); ?>

    <?php $element = $this->fieldset->get('managedTeams'); ?>
    <table class="table table-striped">
        <tbody style="border:0">

    <?php if ( ! isset($isTemplate) || ! $isTemplate ): ?>
    <?php foreach ( $element->getElements() as $teamElement ): ?>
    <?php   $team = $fieldset->getTeam($teamElement->getValue()); ?>
    <?php   if ( $team instanceof Team ): ?>
    <?php     echo $managedTeamTemplate($this, $teamElement, $team); ?>
    <?php   endif; ?>
    <?php endforeach; ?>
    <?php endif; ?>

        </tbody>
    </table>

    <script type="text/javascript">
        var managedTeamsSelectorTemplate = '<?php echo $this->escapeJs($managedTeamTemplate($this, $element->getTemplateElement(), null, true)); ?>';
        var managedTeamIndex = <?php echo $this->escapeJs(count($element)); ?>;

        $(document).on('click', '.rbac-assignment-teamadmin .rbac-assignment-addteam', function() {
            var html = managedTeamsSelectorTemplate.replace(/__teamindex__/g, managedTeamIndex++);
            $('.rbac-assignment-teamadmin table tbody').append(html);
        });
        $(document).on('click', '.rbac-assignment-teamadmin .dropteam', function() {
            $(this).closest('*[data-teamid]').remove();
        });
    </script>

</div>