<?php
use UsaRugbyStats\Competition\Entity\Union;

foreach ( $this->fieldset as $item ) {
    $item->setLabelAttributes(array('class' => 'col-md-2 control-label'));
    $item->setAttributes(array('class' => 'form-control'));
}

$managedUnionTemplate = function($view, $element, $union = null, $isTemplate = false)
{
    $unionId = $view->escapeHtmlAttr($element->getValue());
    $hiddenElement = $isTemplate ? $view->formSelect($element) : $view->formHidden($element);
    $unionName = $view->escapeHtml(( $union instanceof Union ) ? $union->getName() : (string)$union);

    return <<<EOB
            <tr data-unionid="{$unionId}">
                <td>
                    {$hiddenElement}
                    {$unionName}
                </td>
                <td class="col-sm-2" style="text-align:right"><a class="btn btn-xs btn-danger dropunion" title="Remove Union"><i class="glyphicon glyphicon-trash"></i></a></td>
            </tr>
EOB;
}

?>

<div class="rbac-assignment rbac-assignment-unionadmin panel panel-default" data-type="union_admin" data-index="<?php echo $this->escapeHtmlAttr($index); ?>">
    <div class="panel-heading">
        Union Administrator
        <div class="pull-right">
            <a class="btn btn-xs btn-success rbac-assignment-addunion" title="Add Union"><i class="glyphicon glyphicon-plus-sign"></i></a>
            <a class="btn btn-xs btn-danger rbac-assignment-delete" title="Remove Role Assignment"><i class="glyphicon glyphicon-trash"></i></a>
        </div>
    </div>

    <?php echo $this->render('usa-rugby-stats/account-admin/role-assignments/common', array('fieldset' => $fieldset)); ?>

    <?php $element = $this->fieldset->get('managedUnions'); ?>
    <table class="table table-striped">
        <tbody style="border:0">

    <?php if ( ! isset($isTemplate) || ! $isTemplate ): ?>
    <?php foreach ( $element->getElements() as $unionElement ): ?>
    <?php   $union = $fieldset->getUnion($unionElement->getValue()); ?>
    <?php   if ( $union instanceof Union ): ?>
    <?php     echo $managedUnionTemplate($this, $unionElement, $union); ?>
    <?php   endif; ?>
    <?php endforeach; ?>
    <?php endif; ?>

        </tbody>
    </table>

    <script type="text/javascript">
        var managedUnionsSelectorTemplate = '<?php echo $this->escapeJs($managedUnionTemplate($this, $element->getTemplateElement(), null, true)); ?>';
        var managedUnionIndex = <?php echo $this->escapeJs(count($element)); ?>;

        $('.rbac-assignment-unionadmin[data-index=<?php echo $this->escapeHtmlAttr($index); ?>] .rbac-assignment-addunion').click(function() {
            var html = managedUnionsSelectorTemplate.replace(/__unionindex__/g, managedUnionIndex++);
            $(this).closest('.rbac-assignment-unionadmin').find('table tbody').append(html);
        });
        $(document).on('click', '.rbac-assignment-unionadmin[data-index=<?php echo $this->escapeHtmlAttr($index); ?>] .dropunion', function() {
            $(this).closest('*[data-unionid]').remove();
        });
    </script>

</div>