<div class="panel">
    <div class="title">
		<h2><span class="icon-users"></span>Rosters</h2>
    </div>
    <table>
    	<thead>
            <tr>
    	       <th class="home-player"><?=$this->ursTeamLink($match->getHomeTeam(), 'default', ['new_window' => true]); ?></th>
    		   <th></th>
    		   <th class="away-player"><?=$this->ursTeamLink($match->getAwayTeam(), 'default', ['new_window' => true]); ?></th>
    	   </tr>
    	</thead>
    	<tbody>
    	   <?php $homePlayers = $match->getHomeTeam()->getPlayers(); ?>
    	   <?php $awayPlayers = $match->getAwayTeam()->getPlayers(); ?>

    	   <?php foreach ( $this->positions as $pkey => $pname ): ?>
        	<tr>
        		<td class="home-player">
        		  <?php if (isset($homePlayers[$pkey]) && null !== $homePlayers[$pkey]): ?>
        		  <?=$this->ursPlayerLink($homePlayers[$pkey]->getPlayer(), 'default', ['new_window' => true]); ?> - #<?=$this->escapeHtml($homePlayers[$pkey]->getNumber()) ?> 
        		  <?php if ( $homePlayers[$pkey]->isFrontRow() ) echo '<span style="font-weight:bold">(FR)</span>';?>
        		  <?php else: echo '&mdash;'; ?>
        		  <?php endif; ?>
        		</td>
        		<td style="text-align:center"><?=$this->escapeHtml($pname);?></td>
        		<td class="away-player">
        		  <?php if (isset($awayPlayers[$pkey]) && null !== $awayPlayers[$pkey]): ?>
        		  # <?=$this->escapeHtml($awayPlayers[$pkey]->getNumber(), 'default', ['new_window' => true]) ?> - <?=$this->ursPlayerLink($awayPlayers[$pkey]->getPlayer()); ?>
        		  <?php if ( $awayPlayers[$pkey]->isFrontRow() ) echo '<span style="font-weight:bold">(FR)</span>';?>
        		  <?php else: echo '&mdash;'; ?>
        		  <?php endif; ?>
        		</td>
        	</tr>
        	<?php endforeach; ?>
    	</tbody>
    </table>
</div>