<?php $isTemplate = @$isTemplate == true; ?>
<?php $elId = $fieldset->get('id'); ?>
<?php $elAccount = $fieldset->get('account'); ?>
<?php $elStatus = $fieldset->get('membershipStatus'); ?>
<?php $elIdValue = $elId->getValue(); ?>

<tr data-recordid="<?php echo $this->escapeHtmlAttr($elId->getValue()); ?>">
    <?php echo $this->formElement($elId); ?>
    <?php echo $this->formElementErrors($elId); ?>

    <td class="column column-name">
        <table style="width:100%">
            <tr>
                <td width="100">Person:</td>
                <td>
                    <?php $elAccount->setAttribute('class', 'form-control input-sm'); ?>
                    <?php echo $this->formElement($elAccount); ?>
                    <?php echo $this->formElementErrors($elAccount); ?>
                </td>
            </tr>
            <tr>
                <td width="100">Status:</td>
                <td>
                    <?php $elStatus->setAttribute('class', 'form-control input-sm'); ?>
                    <?php echo $this->formElement($elStatus); ?>
                    <?php echo $this->formElementErrors($elStatus); ?>
                </td>
            </tr>
        </table>
    </td>


    <td class="col-sm-2 column column-actions" style="text-align:right; padding-right: 15px;"><a class="btn btn-xs btn-danger dropmember" title="Remove Member"><i class="glyphicon glyphicon-trash"></i></a></td>
</tr>